const q = (id, area, topic, difficulty, text, options, answer, explanation) => {
  const shift = [...id].reduce((sum, character) => sum + character.charCodeAt(0), 0) % options.length;
  return {
    id: `mental-${id}`,
    area,
    topic,
    difficulty,
    tag: "Banco geral",
    text,
    options: [...options.slice(shift), ...options.slice(0, shift)],
    answer: (answer - shift + options.length) % options.length,
    explanation,
  };
};

const pack = (prefix, area, topic, source, items) => items.map((item, index) =>
  q(
    `${prefix}-${String(index + 1).padStart(2, "0")}`,
    area,
    topic,
    item[0],
    item[1],
    item[2],
    item[3],
    `${item[4]} Fonte-base: ${source}.`,
  ),
);

const dementiaQuestions = [
  ...pack("dem-core", "Neurologia", "Demências — conceitos", "NICE NG97 e critérios clínicos contemporâneos", [
    ["Fácil", "Qual achado diferencia melhor transtorno neurocognitivo maior de comprometimento cognitivo leve?", ["Presença de queixa subjetiva", "Interferência da perda cognitiva na independência funcional", "Idade acima de 65 anos", "Alteração em qualquer teste de memória"], 1, "O transtorno maior compromete a independência nas atividades cotidianas; no comprometimento leve, a autonomia global é preservada."],
    ["Média", "Idosa esquece compromissos, mas ainda administra finanças, medicações e transporte usando listas. Testagem confirma declínio discreto. Qual hipótese é mais provável?", ["Delirium", "Comprometimento cognitivo leve", "Demência avançada", "Amnésia dissociativa"], 1, "Declínio objetivo com independência funcional preservada favorece comprometimento cognitivo leve."],
    ["Média", "Ao avaliar suspeita de demência, qual informação funcional é mais útil para definir gravidade clínica?", ["Número de anos de escolaridade isoladamente", "Capacidade atual de manejar finanças, medicamentos e tarefas domésticas", "Presença de cefaleia episódica", "Resultado de uma única dosagem de glicose"], 1, "Atividades instrumentais de vida diária detectam perda de autonomia precoce e ajudam a separar comprometimento leve de demência."],
  ]),
  ...pack("dem-ad-clin", "Neurologia", "Demências — doença de Alzheimer", "NICE NG97", [
    ["Média", "Mulher de 72 anos apresenta evolução insidiosa de repetição de perguntas e dificuldade para aprender informações novas, sem flutuação ou sinais focais. Qual síndrome inicial é mais típica?", ["Amnésia episódica anterógrada", "Ataxia cerebelar", "Afasia motora pura", "Síndrome medular"], 0, "A apresentação amnéstica típica começa com prejuízo de memória episódica recente e aprendizagem de novas informações."],
    ["Difícil", "Em suspeita de doença de Alzheimer, qual domínio deve ser especificamente testado na avaliação cognitiva?", ["Memória episódica verbal", "Força de preensão", "Sensibilidade vibratória", "Acuidade visual isolada"], 0, "A diretriz recomenda incluir teste de memória episódica verbal quando Alzheimer é suspeita."],
    ["Média", "Paciente com Alzheimer inicial lembra melhor fatos antigos do que uma conversa ocorrida há dez minutos. Qual estrutura é comprometida precocemente?", ["Hipocampo e córtex entorrinal", "Córtex visual primário", "Núcleo rubro", "Medula cervical"], 0, "Hipocampo e córtex entorrinal são centrais para consolidação de novas memórias e sofrem comprometimento precoce."],
  ]),
  ...pack("dem-ad-path", "Neurologia", "Demências — doença de Alzheimer", "critérios neuropatológicos e literatura neurológica de referência", [
    ["Média", "Quais alterações neuropatológicas caracterizam a doença de Alzheimer?", ["Placas de beta-amiloide e emaranhados de tau hiperfosforilada", "Corpos de Negri e desmielinização", "Depósito de alfa-sinucleína apenas no tronco", "Granulomas caseosos corticais"], 0, "A neuropatologia combina placas extracelulares de beta-amiloide e emaranhados neurofibrilares de tau."],
    ["Difícil", "A progressão dos emaranhados neurofibrilares na doença de Alzheimer correlaciona-se principalmente com:", ["Disseminação de tau por regiões límbicas e neocorticais", "Depósito de ferro apenas no cerebelo", "Perda exclusiva de neurônios motores", "Inflamação meníngea purulenta"], 0, "A carga e distribuição de tau acompanham melhor a gravidade clínica do que a quantidade isolada de placas."],
    ["Média", "Qual sistema neurotransmissor é alvo dos inibidores da acetilcolinesterase no Alzheimer?", ["Colinérgico", "Histaminérgico periférico", "Glicinérgico medular", "Opioide"], 0, "A perda de projeções colinérgicas do prosencéfalo basal contribui para sintomas cognitivos; o tratamento aumenta acetilcolina sináptica."],
  ]),
  ...pack("dem-ad-gen", "Neurologia", "Demências — genética", "literatura neurológica de referência", [
    ["Difícil", "Família apresenta doença de Alzheimer autossômica dominante com início aos 43 anos em várias gerações. Qual gene é classicamente relacionado?", ["PSEN1", "HTT", "FMR1", "DMD"], 0, "Variantes patogênicas em PSEN1 são causa frequente de Alzheimer familiar de início precoce."],
    ["Média", "Qual alelo aumenta o risco de Alzheimer esporádico tardio, mas não determina isoladamente a doença?", ["APOE ε4", "HLA-B27", "Fator V Leiden", "CCR5-Δ32"], 0, "APOE ε4 é fator de risco, não teste diagnóstico nem causa determinística na maioria dos portadores."],
    ["Difícil", "Qual cenário justifica mais fortemente aconselhamento genético especializado para demência?", ["Múltiplos parentes com demência de início muito precoce em padrão vertical", "Um avô com declínio aos 92 anos", "Esquecimento transitório durante privação de sono", "Queixa sem declínio objetivo"], 0, "Início precoce recorrente em gerações sucessivas sugere herança dominante e merece aconselhamento antes de qualquer teste."],
  ]),
  ...pack("dem-ad-img", "Neurologia", "Demências — neuroimagem", "NICE NG97", [
    ["Média", "Qual padrão de ressonância favorece Alzheimer típico?", ["Atrofia hipocampal e temporal medial", "Lesão expansiva pontina", "Realce leptomeníngeo difuso", "Hematoma epidural"], 0, "Atrofia temporal medial, especialmente hipocampal, é compatível com a apresentação amnéstica típica."],
    ["Difícil", "Quando o diagnóstico etiológico permanece incerto após avaliação clínica e estrutural, qual exame funcional pode ajudar a diferenciar Alzheimer de demência frontotemporal?", ["FDG-PET ou SPECT de perfusão", "Radiografia de crânio", "Eletroneuromiografia", "Doppler venoso de membros"], 0, "Padrões de hipometabolismo ou hipoperfusão podem apoiar a diferenciação quando o resultado mudará a conduta."],
    ["Média", "Por que a neuroimagem estrutural é solicitada na investigação de demência?", ["Para excluir causas estruturais e auxiliar na definição do subtipo", "Para confirmar demência em todos os casos sem história", "Para substituir avaliação funcional", "Para medir diretamente neurotransmissores"], 0, "TC ou RM ajuda a excluir tumor, hematoma e hidrocefalia e pode revelar padrões vasculares ou degenerativos."],
  ]),
  ...pack("dem-dlb", "Neurologia", "Demências — corpos de Lewy", "NICE NG97 e critérios clínicos de DCL", [
    ["Média", "Homem apresenta flutuação cognitiva marcada, alucinações visuais bem formadas e parkinsonismo espontâneo. Qual diagnóstico é mais provável?", ["Demência com corpos de Lewy", "Alzheimer amnéstico típico", "Demência vascular pura", "Hidrocefalia de pressão normal"], 0, "A combinação de flutuações, alucinações visuais e parkinsonismo compõe o núcleo clínico da demência com corpos de Lewy."],
    ["Difícil", "Qual distúrbio do sono frequentemente precede a demência com corpos de Lewy?", ["Transtorno comportamental do sono REM", "Síndrome das pernas inquietas isolada", "Sonambulismo infantil", "Narcolepsia com cataplexia obrigatória"], 0, "A atuação motora de sonhos por perda da atonia do REM pode anteceder sintomas cognitivos por anos."],
    ["Média", "Em paciente com demência e alucinações visuais, qual achado adicional reforça corpos de Lewy?", ["Hipersensibilidade grave a antipsicóticos", "Resposta dramática a anticolinérgicos", "Paralisia facial periférica isolada", "Afasia de condução estável desde a infância"], 0, "Pessoas com DCL podem apresentar piora intensa do parkinsonismo, sedação ou síndrome neuroléptica com antipsicóticos."],
  ]),
  ...pack("dem-dlb-care", "Neurologia", "Demências — corpos de Lewy", "NICE NG97", [
    ["Difícil", "Paciente com demência com corpos de Lewy tem alucinações não ameaçadoras e sem sofrimento. Qual abordagem inicial é preferível?", ["Avaliar gatilhos e evitar antipsicótico automático", "Iniciar haloperidol em alta dose", "Suspender toda medicação crônica", "Indicar ECT sem avaliação"], 0, "Sintomas sem sofrimento podem ser observados; causas ambientais, dor, infecção e medicamentos devem ser revistos antes de fármacos."],
    ["Média", "Qual fármaco pode beneficiar cognição e sintomas neuropsiquiátricos na demência com corpos de Lewy?", ["Rivastigmina", "Biperideno", "Diazepam contínuo", "Fenitoína"], 0, "Inibidores da acetilcolinesterase, como rivastigmina, são opções recomendadas conforme gravidade e tolerância."],
    ["Difícil", "Se antipsicótico for indispensável por risco grave na demência com corpos de Lewy, qual princípio é mais seguro?", ["Menor dose possível, escolha cautelosa e monitorização estreita", "Haloperidol intramuscular fixo por meses", "Combinar dois antipsicóticos típicos", "Não informar familiares sobre riscos"], 0, "A sensibilidade neuroléptica exige decisão especializada, dose mínima e reavaliação frequente."],
  ]),
  ...pack("dem-pdd", "Neurologia", "Demências — Parkinson", "NICE NG97 e critérios clínicos", [
    ["Média", "Parkinsonismo começou seis anos antes do declínio cognitivo que passou a comprometer a autonomia. Qual diagnóstico é mais provável?", ["Demência associada à doença de Parkinson", "Demência com corpos de Lewy pela regra temporal", "Alzheimer pré-clínico", "Paralisia supranuclear progressiva obrigatória"], 0, "Declínio cognitivo surgindo após doença de Parkinson estabelecida por mais de um ano favorece demência da doença de Parkinson."],
    ["Difícil", "Qual perfil cognitivo é comum na demência da doença de Parkinson?", ["Disfunção executiva e visuoespacial com lentificação", "Amnésia global abrupta isolada", "Afasia de Broca pura", "Perda exclusiva de memória semântica"], 0, "Déficits executivos, atenção, velocidade e visuoespaciais são proeminentes em doenças do espectro Lewy."],
    ["Média", "Qual fármaco possui evidência e indicação frequente para demência associada ao Parkinson?", ["Rivastigmina", "Escopolamina", "Amitriptilina", "Haloperidol"], 0, "Rivastigmina pode melhorar sintomas cognitivos; drogas anticolinérgicas tendem a piorá-los."],
  ]),
  ...pack("dem-ftd", "Neurologia", "Demências — frontotemporal", "NICE NG97 e critérios clínicos de DFT", [
    ["Média", "Executivo de 58 anos desenvolve desinibição, perda de empatia, compulsões e hiperoralidade, com memória episódica relativamente preservada no início. Qual hipótese é mais provável?", ["Variante comportamental da demência frontotemporal", "Alzheimer típico", "Delirium hipoativo", "Amnésia global transitória"], 0, "Mudança precoce de personalidade e conduta com disfunção executiva sugere variante comportamental da DFT."],
    ["Difícil", "Qual região cerebral é predominantemente afetada na variante comportamental da DFT?", ["Córtex frontal e temporal anterior", "Córtex calcarino isolado", "Medula torácica", "Núcleos cocleares"], 0, "Degeneração frontal e temporal anterior explica desinibição, apatia, perda de empatia e alterações semânticas."],
    ["Média", "Qual tratamento cognitivo não deve ser oferecido rotineiramente na demência frontotemporal?", ["Donepezila ou memantina", "Intervenções ambientais", "Suporte ao cuidador", "Manejo dirigido de comportamento"], 0, "A diretriz não recomenda inibidores da acetilcolinesterase nem memantina na DFT."],
  ]),
  ...pack("dem-ppa", "Neurologia", "Demências — afasias progressivas", "critérios clínicos de afasia progressiva primária", [
    ["Difícil", "Paciente perde progressivamente o significado das palavras, nomeia mal objetos e mantém fala fluente. Qual variante de afasia progressiva primária é sugerida?", ["Semântica", "Não fluente/agramática", "Logopênica", "Afasia global súbita"], 0, "A variante semântica causa perda de conhecimento conceitual e compreensão de palavras isoladas."],
    ["Difícil", "Fala esforçada, agramatismo e apraxia de fala progressiva apontam para qual variante?", ["Não fluente/agramática", "Semântica", "Logopênica", "Transcortical sensorial aguda"], 0, "A variante não fluente associa produção laboriosa, erros gramaticais e apraxia de fala."],
    ["Difícil", "Pausas por dificuldade de encontrar palavras e repetição de frases prejudicada, com gramática e compreensão de palavras preservadas, sugerem:", ["Variante logopênica", "Variante semântica", "Afasia motora pura", "Mutismo acinético"], 0, "A variante logopênica compromete acesso lexical e memória fonológica; frequentemente tem patologia de Alzheimer."],
  ]),
  ...pack("dem-vasc", "Neurologia", "Demências — vascular", "NICE NG97", [
    ["Média", "Idoso com múltiplos AVCs apresenta declínio em degraus, lentificação, disfunção executiva e sinais focais. Qual etiologia é mais provável?", ["Demência vascular", "Alzheimer puro", "DFT sem doença vascular", "Depressão sazonal"], 0, "Relação temporal com eventos vasculares, curso em degraus e sinais focais favorecem demência vascular."],
    ["Difícil", "Qual perfil é comum na doença de pequenos vasos subcortical?", ["Lentificação, disfunção executiva e alteração da marcha", "Amnésia episódica isolada desde o primeiro dia", "Alucinações visuais obrigatórias", "Agnosia visual pura"], 0, "Circuitos frontossubcorticais são afetados, gerando lentificação, déficit executivo, marcha e sintomas urinários."],
    ["Média", "Grande carga de hiperintensidades vasculares na RM basta para diagnosticar demência vascular?", ["Não; é necessária correlação clínico-funcional", "Sim, independentemente dos sintomas", "Sim, se o paciente tiver mais de 60 anos", "Somente se houver cefaleia"], 0, "A diretriz alerta que carga de lesões isolada não estabelece causalidade; história, perfil e função precisam concordar."],
  ]),
  ...pack("dem-cadasil", "Neurologia", "Demências — vascular", "literatura neurológica de referência", [
    ["Difícil", "Adulto de 42 anos tem enxaqueca com aura, AVCs subcorticais recorrentes e história familiar dominante. Qual doença deve ser lembrada?", ["CADASIL", "MELAS obrigatoriamente materna", "Esclerose lateral amiotrófica", "Miastenia gravis"], 0, "CADASIL associa mutações NOTCH3, enxaqueca, eventos subcorticais e declínio vascular precoce."],
    ["Difícil", "Na RM de paciente com CADASIL, qual localização de lesões é particularmente sugestiva?", ["Polos temporais anteriores e cápsulas externas", "Hipófise isolada", "Nervo óptico apenas", "Cerebelo sem substância branca supratentorial"], 0, "Envolvimento dos polos temporais anteriores e cápsulas externas é característico, embora não exclusivo."],
    ["Média", "Um único infarto talâmico pode causar declínio cognitivo importante apesar de pequena extensão. Esse fenômeno é chamado:", ["Demência por infarto estratégico", "Hidrocefalia ex vacuo", "Amnésia dissociativa", "Encefalopatia hepática"], 0, "Lesões pequenas em tálamo, hipocampo ou regiões angulares podem interromper redes críticas e produzir síndrome cognitiva."],
  ]),
  ...pack("dem-nph", "Neurologia", "Demências — hidrocefalia", "literatura neurológica de referência", [
    ["Média", "Marcha de passos curtos com dificuldade de iniciar, urgência urinária e declínio cognitivo formam a tríade de:", ["Hidrocefalia de pressão normal", "Doença de Huntington", "Miopatia inflamatória", "Esclerose múltipla remitente"], 0, "A marcha costuma ser o sintoma mais precoce e responsivo na hidrocefalia de pressão normal."],
    ["Difícil", "Qual achado de imagem apoia hidrocefalia de pressão normal?", ["Ventriculomegalia desproporcional à atrofia cortical", "Atrofia isolada do hipocampo", "Hematoma epidural", "Calcificação dos núcleos da base isolada"], 0, "A ventriculomegalia, frequentemente com ângulo caloso reduzido e padrão DESH, deve ser correlacionada à clínica."],
    ["Média", "Qual teste pode ajudar a prever resposta à derivação na hidrocefalia de pressão normal?", ["Teste de drenagem lombar com avaliação objetiva da marcha", "Teste ergométrico", "Eletroneuromiografia", "Dosagem de troponina"], 0, "Melhora de marcha após retirada de líquor favorece benefício com derivação, embora teste negativo não exclua totalmente resposta."],
  ]),
  ...pack("dem-pseudo", "Psiquiatria", "Demências — depressão e cognição", "NICE NG97 e NG222", [
    ["Média", "Idosa relata início relativamente rápido de falhas cognitivas junto a humor deprimido, enfatiza seus erros e responde frequentemente 'não sei'. Qual hipótese deve ser investigada?", ["Depressão com comprometimento cognitivo", "Alzheimer confirmado sem avaliação", "DCL obrigatória", "CJD"], 0, "Depressão pode causar prejuízo de atenção, velocidade e memória; avaliação longitudinal e tratamento do humor ajudam no diferencial."],
    ["Difícil", "Qual achado favorece doença neurodegenerativa em vez de comprometimento cognitivo da depressão?", ["Progressão insidiosa com perda funcional corroborada pelo informante", "Queixa intensa desproporcional ao teste", "Variação com motivação", "Início após estressor afetivo"], 0, "Progressão persistente e perda de autonomia observada por terceiros favorecem demência, embora ambas possam coexistir."],
    ["Média", "Após remissão do episódio depressivo, o paciente mantém declínio cognitivo progressivo. Qual conduta é adequada?", ["Prosseguir investigação de transtorno neurocognitivo", "Atribuir tudo à depressão para sempre", "Suspender seguimento", "Diagnosticar simulação"], 0, "Persistência ou progressão após melhora do humor exige reavaliação cognitiva e etiológica."],
  ]),
  ...pack("dem-delirium", "Neurologia", "Demências — delirium", "NICE NG97", [
    ["Fácil", "Qual característica diferencia mais fortemente delirium de demência degenerativa típica?", ["Início agudo com flutuação de atenção", "Idade avançada", "Queixa de memória", "Uso de óculos"], 0, "Delirium surge em horas ou dias e tem desatenção e curso flutuante; demências costumam evoluir em meses ou anos."],
    ["Média", "Paciente internado com declínio cognitivo de causa incerta alterna sonolência e agitação. Se não for possível separar delirium de demência, qual prioridade?", ["Tratar delirium e buscar causa precipitante", "Iniciar donepezila e dar alta", "Aguardar um mês sem investigar", "Aplicar apenas teste de memória"], 0, "Quando há dúvida, delirium deve ser abordado primeiro por indicar condição aguda potencialmente reversível."],
    ["Difícil", "Por que um teste cognitivo isolado não distingue adequadamente delirium de demência?", ["Ambos podem reduzir o escore; atenção, tempo de início e flutuação são essenciais", "Testes nunca detectam cognição", "Delirium sempre preserva atenção", "Demência sempre começa subitamente"], 0, "Contexto clínico, nível de alerta e mudança aguda são indispensáveis para interpretar desempenho cognitivo."],
  ]),
  ...pack("dem-workup", "Neurologia", "Demências — investigação", "NICE NG97", [
    ["Média", "Qual conjunto faz parte da avaliação inicial de suspeita de demência?", ["História com informante, exame físico, teste cognitivo e pesquisa de causas reversíveis", "PET amiloide para todos", "Biópsia cerebral inicial", "Somente autorrelato do paciente"], 0, "A avaliação deve combinar história do paciente e informante, função, exame, cognição e exames dirigidos."],
    ["Média", "Qual combinação laboratorial é frequentemente útil na triagem de causas contribuintes?", ["Hemograma, função tireoidiana, B12, eletrólitos, função renal e hepática conforme contexto", "CK-MB e amilase para todos", "Marcadores tumorais indiscriminados", "Cariotipo de rotina"], 0, "Exames básicos procuram anemia, distúrbios metabólicos, hipotireoidismo e deficiência de B12; outros dependem do risco."],
    ["Difícil", "Qual situação indica investigação neurológica urgente com líquor e testes especializados?", ["Demência rapidamente progressiva em semanas ou poucos meses", "Esquecimento estável há dez anos", "Queixa isolada após plantão", "Declínio compatível com envelhecimento sem perda funcional"], 0, "Progressão rápida exige considerar causas autoimunes, infecciosas, tóxicas, neoplásicas e priônicas potencialmente tratáveis."],
  ]),
  ...pack("dem-screen", "Neurologia", "Demências — avaliação cognitiva", "NICE NG97", [
    ["Fácil", "Um Mini-Cog normal exclui demência em paciente com história funcional convincente?", ["Não", "Sim, sempre", "Somente acima de 80 anos", "Somente se houver depressão"], 0, "Nenhum instrumento breve deve anular história consistente; escolaridade, linguagem e estágio influenciam o resultado."],
    ["Média", "Qual ferramenta baseada em informante pode complementar a história de declínio?", ["IQCODE", "Escala de Glasgow", "Wells", "CURB-65"], 0, "IQCODE avalia mudança cognitiva percebida por alguém que conhece bem o paciente."],
    ["Difícil", "Paciente analfabeto tem baixo escore em teste fortemente dependente de leitura. Qual interpretação é correta?", ["Adequar instrumento e considerar educação antes de concluir demência", "Diagnosticar demência pelo ponto de corte bruto", "Ignorar funcionalidade", "Repetir o mesmo teste até normalizar"], 0, "Escolaridade, idioma, cultura, déficits sensoriais e comunicação podem enviesar escores."],
  ]),
  ...pack("dem-neuropsych", "Neurologia", "Demências — neuropsicologia", "NICE NG97", [
    ["Média", "Quando a avaliação neuropsicológica formal é especialmente útil?", ["Quando presença, causa ou subtipo do déficit permanece incerto", "Em toda queixa leve antes da história", "Somente após demência grave", "Para substituir exame neurológico"], 0, "Testagem detalhada delineia domínios e ajuda em casos diagnósticos limítrofes ou atípicos."],
    ["Difícil", "No Alzheimer hipocampal, qual padrão de memória é esperado?", ["Pouca melhora com pistas e reconhecimento por falha de armazenamento", "Recuperação completa com pistas em todos os casos", "Memória episódica intacta", "Déficit apenas motor"], 0, "Falha de consolidação reduz evocação livre e reconhecimento; disfunção executiva tende a melhorar mais com pistas."],
    ["Difícil", "Lentificação e baixa evocação livre com reconhecimento relativamente preservado sugerem predominantemente:", ["Disfunção frontossubcortical de recuperação", "Síndrome amnéstica hipocampal pura", "Agnosia visual", "Apraxia ideomotora isolada"], 0, "Circuitos executivos prejudicam busca estratégica, enquanto o traço mnésico pode permanecer acessível por reconhecimento."],
  ]),
  ...pack("dem-ache", "Neurologia", "Demências — tratamento", "NICE NG97", [
    ["Média", "Qual opção é indicada para Alzheimer leve a moderado, conforme avaliação individual?", ["Donepezila, galantamina ou rivastigmina", "Haloperidol contínuo", "Levodopa", "Fenobarbital"], 0, "Inibidores da acetilcolinesterase podem oferecer benefício sintomático modesto em cognição e função."],
    ["Difícil", "Paciente em donepezila apresenta síncope e frequência cardíaca de 42 bpm. Qual relação é plausível?", ["Efeito vagotônico com bradicardia", "Hipertireoidismo induzido", "Bloqueio dopaminérgico", "Síndrome serotoninérgica"], 0, "Inibidores da acetilcolinesterase podem causar bradicardia, bloqueio, síncope e sintomas gastrointestinais."],
    ["Média", "A ausência de melhora perceptível imediata após iniciar donepezila significa que o fármaco deve sempre ser suspenso em uma semana?", ["Não; benefício e tolerância devem ser revistos longitudinalmente", "Sim, obrigatoriamente", "Sim, porque cura é esperada em 48 horas", "Não, e nunca deve ser suspenso"], 0, "O objetivo é estabilização ou declínio mais lento; decisão considera tolerância, função, preferência e evolução."],
  ]),
  ...pack("dem-mem", "Neurologia", "Demências — tratamento", "NICE NG97", [
    ["Média", "Em qual situação a memantina é opção típica?", ["Alzheimer moderado com intolerância a inibidor de AChE ou Alzheimer grave", "DFT em qualquer estágio", "Delirium por infecção", "Comprometimento cognitivo leve sem etiologia"], 0, "Memantina é antagonista NMDA usada conforme gravidade e tolerância; não é recomendada para DFT."],
    ["Difícil", "Qual mecanismo descreve a memantina?", ["Antagonismo não competitivo de receptores NMDA", "Inibição irreversível da monoaminoxidase", "Agonismo GABA-A", "Bloqueio de canais de cálcio cardíacos"], 0, "A modulação glutamatérgica por antagonismo NMDA visa reduzir excitotoxicidade sem bloquear transmissão fisiológica."],
    ["Média", "Paciente com Alzheimer moderado já usa donepezila e progride. Qual possibilidade pode ser discutida?", ["Associação de memantina, conforme avaliação clínica", "Adicionar biperideno", "Trocar por haloperidol contínuo", "Suspender todo cuidado não farmacológico"], 0, "A memantina pode ser associada em doença moderada ou grave, individualizando benefício, tolerância e objetivos."],
  ]),
  ...pack("dem-bpsd", "Neurologia", "Demências — sintomas comportamentais", "NICE NG97", [
    ["Média", "Pessoa com demência torna-se agitada subitamente. Qual é o primeiro passo?", ["Buscar dor, delirium, infecção, constipação, ambiente e necessidades não atendidas", "Prescrever antipsicótico automaticamente", "Conter fisicamente", "Ignorar mudança aguda"], 0, "Mudança comportamental aguda frequentemente expressa desconforto ou doença; causas reversíveis vêm antes de sedação."],
    ["Média", "Qual intervenção é primeira linha para agitação sem risco imediato?", ["Abordagem psicossocial e ambiental personalizada", "Haloperidol por tempo indeterminado", "Benzodiazepínico em dose alta", "Isolamento social"], 0, "Atividades significativas, rotina, comunicação, sono e redução de gatilhos devem ser priorizados."],
    ["Difícil", "Quando um antipsicótico pode ser considerado em demência?", ["Risco de dano ou sofrimento grave por psicose/agitação após avaliação de causas", "Toda repetição de perguntas", "Insônia leve isolada", "Para prevenir declínio cognitivo"], 0, "O uso deve ser excepcional, compartilhado, em menor dose e tempo, com reavaliação e discussão de riscos cerebrovasculares e mortalidade."],
  ]),
  ...pack("dem-antichol", "Neurologia", "Demências — medicamentos", "NICE NG97", [
    ["Média", "Qual medicamento pode aumentar carga anticolinérgica e piorar cognição em idoso?", ["Amitriptilina", "Losartana", "Metformina", "Levotiroxina"], 0, "Antidepressivos tricíclicos como amitriptilina têm forte efeito anticolinérgico e podem causar confusão, retenção e quedas."],
    ["Difícil", "Idosa usa oxibutinina, prometazina e amitriptilina. Antes de concluir progressão de demência, deve-se:", ["Revisar e reduzir carga anticolinérgica quando possível", "Adicionar escopolamina", "Duplicar amitriptilina", "Suspender anti-hipertensivos"], 0, "Efeitos anticolinérgicos somam-se e são causa modificável de prejuízo cognitivo."],
    ["Média", "Qual efeito periférico reforça síndrome anticolinérgica em paciente confuso?", ["Boca seca e retenção urinária", "Diarreia e sialorreia", "Miose e broncorreia", "Sudorese intensa"], 0, "Secura, midríase, retenção, taquicardia e redução de sudorese acompanham toxicidade antimuscarínica."],
  ]),
  ...pack("dem-cjd", "Neurologia", "Demências — rapidamente progressivas", "NICE NG97 e critérios de doenças priônicas", [
    ["Difícil", "Declínio cognitivo em semanas, mioclonias, ataxia e complexos periódicos no EEG sugerem:", ["Doença de Creutzfeldt–Jakob", "Alzheimer típico", "DFT lentamente progressiva", "Hidrocefalia de pressão normal"], 0, "A combinação de demência rapidamente progressiva, mioclonia e achados de EEG/RM sugere doença priônica."],
    ["Difícil", "Qual achado de RM é clássico na doença de Creutzfeldt–Jakob esporádica?", ["Restrição à difusão cortical e em caudado/putâmen", "Atrofia hipocampal isolada", "Lesão selar cística", "Hematoma subdural bilateral"], 0, "Cortical ribboning e restrição nos núcleos da base apoiam o diagnóstico no contexto clínico."],
    ["Média", "Diante de demência rapidamente progressiva, qual postura é correta?", ["Encaminhar urgentemente e investigar causas tratáveis e priônicas", "Aguardar um ano", "Iniciar donepezila sem exames", "Assumir envelhecimento"], 0, "Encefalites autoimunes, infecções, tóxicos e alterações metabólicas podem mimetizar doença priônica e requerem rapidez."],
  ]),
  ...pack("dem-mixed", "Neurologia", "Demências — diagnóstico diferencial", "NICE NG97", [
    ["Média", "Paciente tem curso amnéstico progressivo e múltiplos infartos com pioras abruptas. Qual formulação é mais plausível?", ["Demência mista Alzheimer-vascular", "Uma única etiologia obrigatória", "Delirium permanente", "Amnésia global transitória recorrente"], 0, "Patologias neurodegenerativa e vascular frequentemente coexistem e ambas podem contribuir para o declínio."],
    ["Difícil", "Alucinações visuais, flutuação e parkinsonismo em paciente também com amnésia não obrigam excluir Alzheimer porque:", ["Patologias mistas são comuns", "Alzheimer sempre causa parkinsonismo precoce", "Alucinação prova transtorno factício", "Neuroimagem nunca ajuda"], 0, "Copatologia Alzheimer-Lewy é comum; o fenótipo e a contribuição de cada processo devem ser avaliados."],
    ["Média", "Qual fator vascular modificável merece tratamento em qualquer demência com doença cerebrovascular?", ["Hipertensão arterial", "Cor dos olhos", "Lateralidade manual", "Grupo sanguíneo"], 0, "Controle de pressão, diabetes, tabagismo e outros riscos reduz novos eventos, embora não reverta dano estabelecido."],
  ]),
  ...pack("dem-care", "Neurologia", "Demências — cuidado e segurança", "NICE NG97", [
    ["Média", "Paciente com demência leve ainda dirige, mas familiares relatam colisões e desorientação. Qual conduta é adequada?", ["Avaliar segurança para dirigir e orientar conforme legislação local", "Garantir que pode dirigir por ter carteira", "Esperar acidente grave", "Ocultar o risco"], 0, "Diagnóstico isolado não define capacidade, mas sinais de condução insegura exigem avaliação e medidas de proteção."],
    ["Média", "Qual medida reduz risco doméstico em demência moderada?", ["Organizar medicamentos, revisar fogão, quedas e supervisão necessária", "Retirar toda autonomia sem avaliação", "Usar contenção contínua", "Suspender atividade física"], 0, "Plano proporcional inclui segurança medicamentosa, ambiente, nutrição, finanças e apoio ao cuidador."],
    ["Difícil", "Uma pessoa com demência necessariamente perde capacidade para todas as decisões no diagnóstico?", ["Não; capacidade é específica para decisão e momento", "Sim, automaticamente", "Somente familiares têm capacidade", "Capacidade depende apenas do escore cognitivo"], 0, "Capacidade requer compreender, reter, ponderar e comunicar a decisão, com apoio adequado e avaliação específica."],
  ]),
  ...pack("dem-pall", "Neurologia", "Demências — cuidado avançado", "NICE NG97", [
    ["Média", "Quando cuidados paliativos devem ser considerados na demência?", ["Desde o diagnóstico, ajustados às necessidades", "Apenas nas últimas 24 horas", "Somente após suspender todos os tratamentos", "Nunca"], 0, "A abordagem paliativa acompanha a doença, controla sintomas e alinha cuidado a valores e metas."],
    ["Difícil", "Demência avançada com disfagia exige qual abordagem?", ["Avaliar causas reversíveis, segurança da deglutição, conforto e metas de cuidado", "Sonda permanente obrigatória sem discussão", "Suspender oferta oral imediatamente em todos", "Usar estimulante cognitivo em dose alta"], 0, "Decisões nutricionais devem ser individualizadas, com fonoaudiologia quando apropriada e decisão compartilhada."],
    ["Média", "Por que planejamento antecipado é importante na demência?", ["Permite registrar preferências enquanto a pessoa pode participar", "Elimina necessidade de reavaliação", "Transfere automaticamente todas as decisões ao médico", "Garante prognóstico exato"], 0, "Preferências e representantes podem orientar decisões futuras; planos devem ser revistos conforme desejos e situação."],
  ]),
];

const depressionQuestions = [
  ...pack("dep-core", "Psiquiatria", "Depressão — diagnóstico", "NICE NG222 e critérios diagnósticos contemporâneos", [
    ["Fácil", "Quais são os dois sintomas nucleares do episódio depressivo maior?", ["Humor deprimido e perda de interesse ou prazer", "Euforia e fuga de ideias", "Compulsões e tiques", "Alucinações e catalepsia obrigatórias"], 0, "Pelo menos um dos sintomas nucleares deve estar presente, acompanhado de outros sintomas e prejuízo clínico."],
    ["Média", "Paciente apresenta anedonia, fadiga, culpa, insônia e baixa concentração por três semanas, com prejuízo acadêmico. Qual hipótese é mais provável?", ["Episódio depressivo", "Transtorno de pânico isolado", "Delirium", "Hipomania"], 0, "Duração, conjunto de sintomas e prejuízo funcional sustentam episódio depressivo após excluir bipolaridade, substâncias e causas médicas."],
    ["Média", "Qual sintoma não é necessário para diagnosticar episódio depressivo maior?", ["Ideação suicida", "Humor deprimido ou anedonia", "Prejuízo ou sofrimento clinicamente significativo", "Conjunto de sintomas durante a maior parte dos dias"], 0, "Ideação suicida aumenta gravidade e risco, mas não precisa estar presente para o diagnóstico."],
  ]),
  ...pack("dep-duration", "Psiquiatria", "Depressão — diagnóstico", "NICE NG222 e critérios diagnósticos contemporâneos", [
    ["Fácil", "Qual duração mínima típica dos sintomas é exigida para episódio depressivo maior?", ["Duas semanas", "Dois dias", "Seis meses", "Um ano"], 0, "Os sintomas devem persistir por pelo menos duas semanas, representando mudança do funcionamento prévio."],
    ["Média", "Sintomas depressivos duram cinco dias após reprovação, sem prejuízo importante nem risco. Qual conclusão é mais prudente?", ["Avaliar sofrimento e acompanhar, sem rotular automaticamente episódio maior", "Diagnosticar depressão maior pelo evento", "Iniciar ECT", "Diagnosticar bipolaridade"], 0, "Tristeza contextual breve não basta; intensidade, duração, sintomas associados e função orientam o diagnóstico."],
    ["Difícil", "Humor deprimido crônico na maior parte do tempo por anos, sem longos períodos assintomáticos, sugere:", ["Transtorno depressivo persistente", "Ciclotimia obrigatória", "Delirium", "Transtorno psicótico breve"], 0, "Curso crônico exige avaliação de transtorno depressivo persistente e episódios maiores sobrepostos."],
  ]),
  ...pack("dep-screen", "Psiquiatria", "Depressão — rastreio e avaliação", "NICE NG222", [
    ["Fácil", "Quais perguntas breves ajudam a identificar possível depressão?", ["Humor deprimido/desesperança e pouco interesse/prazer no último mês", "Febre e tosse", "Tontura e zumbido", "Dor lombar e edema"], 0, "As duas perguntas nucleares funcionam como identificação inicial, não como diagnóstico completo."],
    ["Média", "Um PHQ-9 elevado confirma sozinho depressão maior?", ["Não; requer avaliação clínica, funcional e diferencial", "Sim, sempre", "Somente em homens", "Somente com neuroimagem"], 0, "Escalas quantificam sintomas e resposta, mas não substituem história, risco, bipolaridade e causas clínicas."],
    ["Difícil", "Ao avaliar depressão, qual conjunto contextual não deve ser omitido?", ["Função, relacionamentos, trauma, álcool/drogas, condições médicas e tratamentos prévios", "Apenas escore numérico", "Somente história familiar", "Somente exame físico"], 0, "Formulação ampla identifica precipitantes, fatores mantenedores, proteção, comorbidades e barreiras terapêuticas."],
  ]),
  ...pack("dep-suicide", "Psiquiatria", "Depressão — risco suicida", "NICE NG222", [
    ["Fácil", "Como investigar suicídio em pessoa com depressão?", ["Perguntar diretamente sobre pensamentos, intenção, plano e meios", "Evitar perguntar para não induzir", "Perguntar apenas à família", "Esperar tentativa"], 0, "Perguntar de forma clara não induz suicídio e é essencial para estratificar risco e proteção."],
    ["Média", "Paciente relata plano suicida específico, acesso ao meio e intenção para hoje. Qual conduta?", ["Avaliação urgente, proteção imediata e serviço especializado", "Retorno em seis meses", "Prescrever grande quantidade de tricíclico", "Deixá-lo sozinho para refletir"], 0, "Plano, intenção e acesso indicam risco imediato; segurança, supervisão e encaminhamento urgente são prioritários."],
    ["Difícil", "Ao prescrever antidepressivo para paciente com risco de overdose, qual princípio é adequado?", ["Considerar toxicidade e limitar quantidade dispensada", "Preferir sempre tricíclico em grande estoque", "Não acompanhar nas primeiras semanas", "Suspender pergunta sobre risco"], 0, "Escolha e dispensação devem reduzir letalidade potencial, com seguimento próximo e plano de segurança."],
  ]),
  ...pack("dep-severity", "Psiquiatria", "Depressão — gravidade", "NICE NG222", [
    ["Média", "Qual achado torna um episódio depressivo mais grave?", ["Sintomas psicóticos, risco suicida ou incapacidade funcional intensa", "Tristeza leve sem prejuízo", "Uma noite mal dormida", "Preferência por ficar sozinho no fim de semana"], 0, "Gravidade integra número e intensidade de sintomas, prejuízo, psicose, autoabandono e risco."],
    ["Difícil", "Delírio de culpa irreal e vozes acusatórias congruentes com humor em depressão grave indicam:", ["Depressão psicótica", "Esquizofrenia obrigatória", "Hipomania", "Transtorno de adaptação leve"], 0, "Psicose pode ocorrer em depressão grave e frequentemente é congruente com culpa, ruína, doença ou punição."],
    ["Média", "Paciente deprimido parou de comer e beber, permanece imóvel e quase não responde. Qual síndrome grave deve ser avaliada?", ["Catatonia", "Acatisia", "Síndrome cerebelar", "Distonia focal"], 0, "Estupor, mutismo, negativismo e alterações motoras sugerem catatonia, emergência tratável."],
  ]),
  ...pack("dep-mel", "Psiquiatria", "Depressão — especificadores", "literatura psiquiátrica de referência", [
    ["Média", "Anedonia intensa, ausência de reatividade, despertar precoce, piora matinal e culpa excessiva sugerem qual especificador?", ["Características melancólicas", "Características atípicas", "Padrão sazonal", "Início no periparto"], 0, "Melancolia associa perda de prazer/reatividade e sinais vegetativos típicos, retardo ou agitação e culpa."],
    ["Difícil", "Qual alteração psicomotora pode acompanhar depressão melancólica?", ["Retardo ou agitação observável", "Coreia obrigatória", "Tremor de intenção isolado", "Fasciculações"], 0, "A mudança psicomotora deve ser perceptível por outros, não apenas sensação subjetiva de lentidão."],
    ["Média", "Paciente com depressão melancólica relata sono excessivo e aumento do apetite. Isso é:", ["Menos típico e sugere avaliar características atípicas ou mistura de sintomas", "Obrigatório para melancolia", "Prova de mania", "Prova de simulação"], 0, "Melancolia tende a despertar precoce e perda de apetite; hipersonia e hiperfagia são mais ligadas ao padrão atípico."],
  ]),
  ...pack("dep-atyp", "Psiquiatria", "Depressão — especificadores", "literatura psiquiátrica de referência", [
    ["Média", "Reatividade do humor, hipersonia, hiperfagia, sensação de peso nos membros e sensibilidade à rejeição sugerem:", ["Depressão com características atípicas", "Melancolia", "Delirium", "Catatonia"], 0, "Reatividade do humor é central e pode acompanhar sintomas vegetativos reversos e sensibilidade interpessoal."],
    ["Difícil", "O termo 'atípica' significa que essa apresentação é rara ou não é depressão?", ["Não; é um especificador clínico reconhecido", "Sim, significa simulação", "Sim, exclui transtorno do humor", "Significa psicose obrigatória"], 0, "O nome histórico não implica raridade nem ausência de depressão; descreve um conjunto específico de sintomas."],
    ["Média", "Qual sintoma diferencia mais diretamente características atípicas das melancólicas?", ["Humor melhora diante de eventos positivos", "Culpa", "Baixa concentração", "Ideação de morte"], 0, "Reatividade do humor contrasta com a perda de reatividade típica da melancolia."],
  ]),
  ...pack("dep-season", "Psiquiatria", "Depressão — especificadores", "NICE NG222 e literatura psiquiátrica de referência", [
    ["Média", "Episódios depressivos surgem todo inverno e remitem na primavera por vários anos. Qual padrão é sugerido?", ["Padrão sazonal", "Ciclagem rápida obrigatória", "Transtorno psicótico", "Delirium recorrente"], 0, "Relação temporal regular com estação e remissão característica permite considerar padrão sazonal."],
    ["Difícil", "Antes de atribuir depressão ao padrão sazonal, é importante:", ["Confirmar repetição do padrão e excluir estressores sazonais coincidentes", "Basear-se em um único episódio", "Solicitar PET obrigatório", "Excluir qualquer tratamento"], 0, "O padrão precisa predominar sobre episódios não sazonais e não ser explicado por eventos recorrentes específicos."],
    ["Média", "Episódio começa durante a gestação ou nas semanas após o parto. Qual especificador é relevante?", ["Início no periparto", "Padrão catatônico obrigatório", "Características mistas obrigatórias", "Padrão sazonal"], 0, "Depressão perinatal exige avaliação de vínculo, suporte, segurança materna e do bebê e escolha terapêutica individualizada."],
  ]),
  ...pack("dep-bipolar", "Psiquiatria", "Depressão — diferencial bipolar", "NICE NG222 e literatura psiquiátrica de referência", [
    ["Média", "Antes de iniciar antidepressivo, qual história deve ser pesquisada ativamente?", ["Períodos de energia aumentada, menor necessidade de sono e impulsividade", "Somente cefaleia", "Alergia alimentar", "Miopia"], 0, "Episódios de mania ou hipomania mudam o diagnóstico e evitam antidepressivo em monoterapia inadequada."],
    ["Difícil", "Paciente deprimido relata quatro dias prévios de humor elevado, fala aumentada, apenas três horas de sono sem cansaço e gastos impulsivos. Isso sugere:", ["Hipomania e possível transtorno bipolar", "Insônia primária apenas", "Depressão unipolar confirmada", "Delirium hipoativo"], 0, "Mudança episódica de energia e funcionamento com menor necessidade de sono exige avaliação bipolar."],
    ["Média", "Qual achado durante antidepressivo levanta suspeita de bipolaridade?", ["Virada para mania ou hipomania", "Náusea transitória", "Melhora gradual", "Boca seca leve"], 0, "Ativação sustentada com sintomas sindrômicos deve ser diferenciada de ansiedade inicial ou acatisia."],
  ]),
  ...pack("dep-grief", "Psiquiatria", "Depressão — diagnóstico diferencial", "NICE NG222", [
    ["Média", "Luto e depressão maior são mutuamente exclusivos?", ["Não; um episódio depressivo pode ocorrer durante o luto", "Sim, por um ano", "Sim, se houve perda familiar", "Somente em idosos"], 0, "O contexto de perda não impede diagnóstico; persistência, desesperança, culpa global, anedonia e risco orientam avaliação."],
    ["Difícil", "Qual característica favorece luto não complicado em vez de episódio depressivo maior?", ["Dor em ondas ligada a lembranças, com autoestima geralmente preservada", "Desvalia global persistente", "Anedonia pervasiva", "Ideação suicida por autodepreciação"], 0, "No luto, emoções positivas e conexão podem coexistir; na depressão, negatividade tende a ser mais difusa."],
    ["Média", "Sintomas emocionais após estressor causam prejuízo, mas não preenchem episódio depressivo. Qual hipótese pode ser considerada?", ["Transtorno de adaptação", "Demência", "Catatonia", "Mania"], 0, "Transtorno de adaptação é resposta desproporcional a estressor identificável sem preencher melhor outro transtorno."],
  ]),
  ...pack("dep-med", "Psiquiatria", "Depressão — causas médicas", "NICE NG222", [
    ["Fácil", "Qual doença endócrina pode mimetizar depressão com fadiga e lentificação?", ["Hipotireoidismo", "Hipertensão essencial isolada", "Miopia", "Rinite alérgica leve"], 0, "História e exame orientam TSH; hipotireoidismo pode produzir humor baixo, lentificação, constipação e intolerância ao frio."],
    ["Média", "Humor deprimido começou após introdução de corticosteroide sistêmico. Qual passo é importante?", ["Revisar relação temporal e discutir ajuste seguro do medicamento", "Suspender abruptamente por conta própria", "Ignorar fármacos", "Diagnosticar transtorno de personalidade"], 0, "Medicamentos e substâncias podem induzir sintomas; corticosteroides exigem manejo clínico cauteloso, não retirada abrupta indiscriminada."],
    ["Difícil", "Depressão, apatia, déficit executivo e movimentos coreicos em adulto com história familiar sugerem:", ["Doença de Huntington", "Alzheimer típico", "Miastenia", "Neuropatia diabética"], 0, "Sintomas psiquiátricos podem anteceder a coreia na doença de Huntington; contexto motor e familiar é decisivo."],
  ]),
  ...pack("dep-ssri", "Psiquiatria", "Depressão — antidepressivos", "NICE NG222", [
    ["Fácil", "Qual classe costuma ser primeira escolha farmacológica pela relação entre eficácia e tolerabilidade?", ["ISRS", "Barbitúricos", "Antipsicóticos típicos isolados", "Anticolinérgicos"], 0, "ISRS são frequentemente escolhidos, mas preferência, sintomas, interações e resposta prévia individualizam a decisão."],
    ["Média", "Qual efeito adverso é comum com ISRS?", ["Disfunção sexual", "Fibrose pulmonar", "Agranulocitose obrigatória", "Nefrolitíase em todos"], 0, "Náusea, alterações do sono e disfunção sexual são frequentes; o perfil varia entre fármacos."],
    ["Difícil", "Idosa inicia sertralina e evolui com confusão, sódio de 122 mEq/L e osmolaridade baixa. Qual mecanismo é provável?", ["SIADH associada ao antidepressivo", "Diabetes insípido", "Hipercalcemia", "Cetoacidose"], 0, "ISRS podem precipitar hiponatremia por SIADH, especialmente em idosos, baixo peso e uso de diuréticos."],
  ]),
  ...pack("dep-snri", "Psiquiatria", "Depressão — antidepressivos", "NICE NG222", [
    ["Média", "Qual antidepressivo requer atenção à pressão arterial, sobretudo em doses maiores?", ["Venlafaxina", "Escitalopram", "Mirtazapina", "Agomelatina"], 0, "O efeito noradrenérgico da venlafaxina pode elevar pressão e frequência; monitorização depende do risco."],
    ["Média", "Depressão acompanhada de dor neuropática pode favorecer discussão de qual opção?", ["Duloxetina", "Haloperidol", "Biperideno", "Fenobarbital"], 0, "Duloxetina atua em serotonina e noradrenalina e também possui indicação para síndromes dolorosas específicas."],
    ["Difícil", "Esquecimento de doses de venlafaxina produz tontura, irritabilidade e sensações de choque. Qual explicação?", ["Síndrome de descontinuação", "Síndrome neuroléptica maligna", "Intoxicação anticolinérgica", "Hipomania obrigatória"], 0, "Meia-vida curta aumenta sintomas de retirada; redução deve ser gradual e individualizada."],
  ]),
  ...pack("dep-other", "Psiquiatria", "Depressão — antidepressivos", "NICE NG222", [
    ["Média", "Paciente com depressão, insônia e perda de apetite pode se beneficiar do perfil de qual fármaco?", ["Mirtazapina", "Bupropiona", "Fluoxetina pela sedação intensa", "Metilfenidato obrigatório"], 0, "Mirtazapina tende a sedar e aumentar apetite, o que pode ser útil ou indesejável conforme o caso."],
    ["Média", "Qual antidepressivo costuma causar menos disfunção sexual e pode ajudar na cessação do tabagismo?", ["Bupropiona", "Paroxetina", "Clomipramina", "Fenelzina"], 0, "Bupropiona atua em noradrenalina/dopamina, tem menor carga sexual e é usada para tabagismo."],
    ["Difícil", "Em qual situação bupropiona deve ser evitada por aumentar risco convulsivo?", ["Transtorno alimentar purgativo ativo", "Hipotireoidismo tratado", "Rinite", "Miopia"], 0, "Bulimia, anorexia, epilepsia e retirada abrupta de álcool ou sedativos aumentam risco de convulsão."],
  ]),
  ...pack("dep-tca", "Psiquiatria", "Depressão — antidepressivos", "NICE NG222", [
    ["Média", "Por que tricíclicos exigem cautela em paciente com risco suicida?", ["Alta toxicidade cardíaca e neurológica em overdose", "Não atravessam barreira hematoencefálica", "Nunca funcionam", "Causam dependência em todos"], 0, "Bloqueio de canais de sódio pode causar QRS largo, arritmia, hipotensão e convulsões."],
    ["Difícil", "Overdose de amitriptilina com QRS alargado e hipotensão deve ser tratada prioritariamente com:", ["Bicarbonato de sódio intravenoso", "Flumazenil", "Naloxona isolada", "Cálcio oral"], 0, "Alcalinização e carga de sódio reduzem bloqueio de canais e são fundamentais na cardiotoxicidade por tricíclicos."],
    ["Média", "Qual conjunto de efeitos da amitriptilina decorre de ação anticolinérgica?", ["Boca seca, constipação, retenção urinária e visão turva", "Diarreia, sialorreia e miose", "Tosse e broncorreia", "Hipoglicemia e urticária"], 0, "Bloqueio muscarínico é especialmente problemático em idosos, glaucoma de ângulo fechado, retenção e comprometimento cognitivo."],
  ]),
  ...pack("dep-maoi", "Psiquiatria", "Depressão — interações", "NICE NG222", [
    ["Difícil", "Pessoa em fenelzina ingere grande quantidade de alimento rico em tiramina e apresenta cefaleia e hipertensão grave. Qual mecanismo?", ["Excesso de catecolaminas por interação com IMAO", "Deficiência aguda de serotonina", "Bloqueio colinérgico", "Hipoglicemia por insulina"], 0, "IMAO irreversível impede metabolismo de tiramina, podendo precipitar crise hipertensiva."],
    ["Média", "Agitação, hiperreflexia, clônus, sudorese e febre após combinar fármacos serotoninérgicos sugerem:", ["Síndrome serotoninérgica", "Síndrome anticolinérgica", "Catatonia simples", "Demência com Lewy"], 0, "Clônus e hiperreflexia ajudam a distinguir toxicidade serotoninérgica de síndrome neuroléptica maligna."],
    ["Difícil", "Ao trocar entre antidepressivo serotoninérgico e IMAO, qual cuidado é essencial?", ["Respeitar período de washout apropriado", "Sobrepor doses máximas", "Suspender seguimento", "Usar tiramina para teste"], 0, "A sobreposição pode ser fatal; o intervalo depende das meias-vidas, sendo especialmente longo após fluoxetina."],
  ]),
  ...pack("dep-stop", "Psiquiatria", "Depressão — manejo farmacológico", "NICE NG222", [
    ["Média", "Após remissão, paciente interrompe paroxetina abruptamente e apresenta tontura, ansiedade e sintomas gripais. Qual conduta preventiva seria melhor?", ["Redução gradual planejada", "Interrupção em dias alternados sem orientação", "Aumento indefinido", "Troca direta por IMAO"], 0, "Retirada gradual reduz sintomas; ritmo deve considerar meia-vida, dose, duração e experiência prévia."],
    ["Difícil", "Como diferenciar descontinuação de recaída?", ["Descontinuação começa logo após redução e inclui sintomas físicos incomuns na recaída", "São sempre idênticas", "Recaída começa minutos após esquecer uma dose", "Descontinuação dura anos obrigatoriamente"], 0, "Tontura, choques e náusea de início rápido favorecem retirada; recaída tende a reproduzir o padrão depressivo gradualmente."],
    ["Média", "Paciente deseja parar antidepressivo após melhora. Qual abordagem é adequada?", ["Decisão compartilhada com redução em etapas e monitorização", "Dizer que nunca poderá parar", "Suspender imediatamente", "Substituir por álcool"], 0, "Planejamento reduz retirada e permite detectar retorno de sintomas, respeitando risco de recaída e preferência."],
  ]),
  ...pack("dep-acute", "Psiquiatria", "Depressão — tratamento", "NICE NG222", [
    ["Média", "Quando revisar resposta, adesão, efeitos e risco após iniciar tratamento?", ["Em geral entre 2 e 4 semanas, antes se houver risco", "Somente após um ano", "Apenas quando o paciente pedir", "Nunca"], 0, "Seguimento precoce é necessário; jovens e pessoas com risco podem exigir contato ainda mais cedo."],
    ["Difícil", "Ausência de melhora após uma semana em dose inicial significa resistência terapêutica?", ["Não; verificar tempo, dose, adesão, diagnóstico e comorbidades", "Sim, e indicar ECT imediatamente", "Sim, e combinar três antidepressivos", "Prova de bipolaridade"], 0, "Resposta exige ensaio adequado e avaliação sistemática; uma semana geralmente é insuficiente."],
    ["Média", "Após remissão de primeiro episódio, por que manter antidepressivo por um período?", ["Reduzir risco de recaída enquanto a recuperação se consolida", "Produzir dependência", "Curar em 24 horas", "Impedir qualquer emoção"], 0, "Continuação costuma durar pelo menos meses após remissão e é individualizada pelo risco e preferência."],
  ]),
  ...pack("dep-psych", "Psiquiatria", "Depressão — psicoterapia", "NICE NG222", [
    ["Fácil", "Qual psicoterapia trabalha pensamentos, comportamentos e padrões mantenedores da depressão?", ["Terapia cognitivo-comportamental", "Hipnose obrigatória", "Terapia aversiva", "Privação sensorial"], 0, "TCC é tratamento estruturado com evidência para episódios depressivos e prevenção de recaída."],
    ["Média", "Ativação comportamental concentra-se principalmente em:", ["Reduzir evitação e aumentar atividades alinhadas a reforço e valores", "Interpretar sonhos exclusivamente", "Induzir sedação", "Suprimir memórias"], 0, "Planejamento gradual de atividades rompe ciclo de inatividade, perda de reforço e piora do humor."],
    ["Difícil", "Depressão relacionada a luto, transição de papéis e conflitos pode ser abordada por:", ["Psicoterapia interpessoal", "Exposição a tiramina", "Estimulação vagal caseira", "Contenção"], 0, "TIP focaliza relações, papéis sociais, perdas e déficits interpessoais associados ao episódio."],
  ]),
  ...pack("dep-severe", "Psiquiatria", "Depressão — tratamento", "NICE NG222", [
    ["Média", "Para novo episódio mais grave, qual estratégia possui forte racional clínico?", ["Combinação de antidepressivo e TCC individual, conforme preferência", "Somente observação em todo caso", "Antipsicótico típico isolado", "Suspender contato social"], 0, "Tratamentos combinados podem ser oferecidos como primeira linha, com decisão compartilhada e alternativas válidas."],
    ["Difícil", "Depressão psicótica costuma exigir consideração de:", ["Antidepressivo associado a antipsicótico e cuidado especializado", "ISRS em dose mínima sem seguimento sempre", "Psicoestimulante isolado", "Nenhum tratamento"], 0, "A combinação é frequentemente usada; ECT também pode ser apropriada conforme gravidade, urgência e preferência."],
    ["Média", "Paciente com autoabandono, desidratação e depressão grave necessita:", ["Avaliação urgente do nível de cuidado e suporte médico-psiquiátrico", "Consulta eletiva em seis meses", "Apenas material educativo", "Suspensão de alimentação"], 0, "Risco médico e incapacidade de autocuidado podem justificar manejo intensivo ou internação."],
  ]),
  ...pack("dep-ect", "Psiquiatria", "Depressão — ECT", "NICE NG222", [
    ["Média", "Qual cenário favorece eletroconvulsoterapia?", ["Depressão grave com necessidade de resposta rápida, preferência ou falha de outros tratamentos", "Tristeza leve por dois dias", "Ansiedade de prova isolada", "Insônia sem depressão"], 0, "ECT é particularmente eficaz em depressão grave, psicótica, catatônica ou com risco vital."],
    ["Difícil", "Qual efeito adverso cognitivo deve ser discutido antes da ECT?", ["Amnésia peri-tratamento e possível lacuna autobiográfica", "Demência inevitável", "Afasia permanente obrigatória", "Paralisia flácida"], 0, "Alterações de memória variam com técnica, posição dos eletrodos, dose e vulnerabilidade individual."],
    ["Média", "ECT moderna é realizada:", ["Sob anestesia e relaxamento muscular, com monitorização", "Sem anestesia", "Como punição", "Somente em paciente acordado e imobilizado"], 0, "Procedimento contemporâneo usa anestesia breve, bloqueio neuromuscular e monitorização clínica e eletroencefalográfica."],
  ]),
  ...pack("dep-resistant", "Psiquiatria", "Depressão — resistência terapêutica", "NICE NG222", [
    ["Difícil", "Antes de rotular depressão resistente, qual passo é essencial?", ["Rever diagnóstico, bipolaridade, adesão, dose, duração, substâncias e comorbidades", "Contar apenas número de receitas", "Ignorar psicoterapia", "Solicitar cirurgia"], 0, "Pseudorresistência decorre frequentemente de ensaio inadequado, diagnóstico incompleto ou fatores mantenedores."],
    ["Média", "Após resposta insuficiente a antidepressivo adequado, qual opção pode ser discutida?", ["Troca, combinação com psicoterapia ou potencialização especializada", "Abandonar todo tratamento", "Duplicar dose sem limite", "Combinar IMAO e ISRS"], 0, "Próxima etapa depende de resposta parcial, tolerância, preferência e risco; combinações exigem segurança."],
    ["Difícil", "Qual agente é usado como potencializador em depressão resistente sob monitorização?", ["Lítio", "Biperideno", "Fenitoína", "Amoxicilina"], 0, "Lítio e alguns antipsicóticos de segunda geração têm evidência; lítio requer função renal/tireoidiana, níveis e atenção à toxicidade."],
  ]),
  ...pack("dep-special", "Psiquiatria", "Depressão — populações especiais", "NICE NG222 e princípios de psicofarmacologia perinatal", [
    ["Média", "Em idoso iniciando antidepressivo, qual princípio é apropriado?", ["Considerar comorbidades, interações, quedas e hiponatremia, com acompanhamento", "Usar tricíclico em alta dose sempre", "Ignorar função renal", "Evitar toda psicoterapia"], 0, "O tratamento é eficaz, mas requer revisão de polifarmácia e vulnerabilidades; não significa subtratar."],
    ["Difícil", "Gestante com depressão grave deve interromper todo tratamento automaticamente?", ["Não; riscos da doença e de cada opção devem ser ponderados individualmente", "Sim, sempre", "Somente álcool é seguro", "ECT nunca pode ser considerada"], 0, "Depressão não tratada também traz riscos; decisão compartilhada considera gravidade, histórico, evidência e acompanhamento obstétrico-psiquiátrico."],
    ["Média", "No pós-parto, qual achado exige avaliação urgente?", ["Ideias de ferir a si ou o bebê, psicose ou desorganização intensa", "Choro breve com suporte preservado", "Cansaço após uma noite ruim", "Dúvida comum sobre amamentação"], 0, "Risco, psicose e possível transtorno bipolar no pós-parto são emergências para proteção da mãe e do bebê."],
  ]),
  ...pack("dep-young", "Psiquiatria", "Depressão — jovens", "NICE NG222", [
    ["Média", "Ao iniciar antidepressivo em adulto jovem, qual monitorização merece ênfase?", ["Agitação, piora do humor e ideação suicida nas primeiras semanas", "Apenas peso anual", "Somente glicemia", "Nenhum contato até três meses"], 0, "Início ou mudança de dose é período de vigilância, com orientação clara sobre como buscar ajuda."],
    ["Difícil", "Irritabilidade persistente pode ser manifestação de depressão em jovens?", ["Sim, devendo ser avaliada com outros sintomas e prejuízo", "Nunca", "Somente se houver psicose", "Prova de transtorno antissocial"], 0, "Apresentações variam; irritabilidade, queda acadêmica, retraimento, sono e risco devem ser investigados."],
    ["Média", "Qual elemento aumenta segurança do plano terapêutico de jovem com ideação passiva?", ["Plano de segurança, rede de apoio, restrição de meios e seguimento próximo", "Promessa de nunca mais pensar nisso como única medida", "Estoque grande de medicamentos", "Sigilo absoluto mesmo com risco iminente"], 0, "Intervenções concretas e colaborativas reduzem acesso a meios e definem sinais, contatos e ações de crise."],
  ]),
  ...pack("dep-relapse", "Psiquiatria", "Depressão — prevenção de recaída", "NICE NG222", [
    ["Média", "Qual fator aumenta risco de recaída depressiva?", ["Múltiplos episódios prévios e sintomas residuais", "Remissão completa duradoura", "Boa rede de apoio", "Adesão ao tratamento"], 0, "Recorrência, gravidade, cronicidade e sintomas residuais justificam prevenção mais prolongada."],
    ["Difícil", "Qual psicoterapia possui evidência específica para prevenção de recaída em depressão recorrente?", ["TCC ou terapia cognitiva baseada em mindfulness", "Terapia aversiva", "Privação de sono crônica", "Isolamento"], 0, "TCC e MBCT ajudam a reconhecer padrões e responder a sinais precoces, especialmente em recorrência."],
    ["Média", "Qual é um bom plano de prevenção após remissão?", ["Identificar sinais precoces, gatilhos, ações, contatos e estratégia de manutenção", "Suspender seguimento imediatamente", "Evitar discutir recaída", "Manter dose sem revisão vitalícia para todos"], 0, "Plano individualizado inclui hábitos, tratamento, rede e resposta rápida, revisado periodicamente."],
  ]),
  ...pack("dep-chronic", "Psiquiatria", "Depressão — curso crônico", "NICE NG222", [
    ["Média", "Em sintomas depressivos crônicos com prejuízo, qual tratamento pode ser oferecido?", ["TCC, antidepressivo ou combinação conforme necessidade e preferência", "Nenhuma intervenção", "Antipsicótico típico obrigatório", "ECT domiciliar"], 0, "Tratamentos psicológicos e farmacológicos são válidos; curso longo exige metas realistas e revisão de fatores mantenedores."],
    ["Difícil", "Na TCC para depressão crônica, quais processos merecem foco?", ["Evitação, ruminação e dificuldades interpessoais", "Somente sonhos", "Apenas memória remota", "Somente dieta"], 0, "Esses processos mantêm inatividade, desesperança e desconexão, devendo integrar a formulação."],
    ["Média", "Paciente diz que 'sempre foi assim' e nunca buscou ajuda. Qual resposta clínica é melhor?", ["Explorar cronicidade, função e oferecer tratamento sem normalizar o sofrimento", "Concluir que personalidade não trata", "Negar depressão", "Indicar alta"], 0, "Pessoas com sintomas crônicos podem não reconhecê-los como tratáveis; abordagem compassiva facilita acesso."],
  ]),
];

export const mentalHealthQuestions = [...dementiaQuestions, ...depressionQuestions];
