const p = (id, area, topic, condition, vignette, hallmark, test, treatment, complication, risk, prevention, followUp) => ({
  id, area, topic, condition, vignette, hallmark, test, treatment, complication, risk, prevention, followUp
});

const profiles = [
  p("car-01","Cardiologia","Insuficiência cardíaca","Insuficiência cardíaca com fração de ejeção reduzida","dispneia progressiva, ortopneia, estertores e fração de ejeção de 30%","terceira bulha e sinais de congestão","ecocardiograma transtorácico","terapia modificadora de prognóstico com ARNI/IECA, betabloqueador, antagonista mineralocorticoide e inibidor de SGLT2, conforme tolerância","edema agudo de pulmão e morte súbita","infarto prévio e hipertensão","controle pressórico e tratamento da cardiopatia de base","reavaliar sintomas, função renal, potássio e fração de ejeção após otimização"),
  p("car-02","Cardiologia","Valvopatias","Estenose aórtica importante","idoso com angina, síncope aos esforços e dispneia","sopro sistólico ejetivo irradiado para carótidas e pulso parvus et tardus","ecocardiograma com medida de área e gradiente valvar","substituição valvar no paciente sintomático com estenose importante","morte súbita e insuficiência cardíaca","valva aórtica bicúspide ou calcificação degenerativa","controle de fatores cardiovasculares, sem terapia capaz de reverter a estenose","seguimento ecocardiográfico e avaliação em equipe valvar"),
  p("car-03","Cardiologia","Arritmias","Fibrilação atrial","palpitações e pulso irregularmente irregular sem ondas P organizadas","intervalos RR irregularmente irregulares","eletrocardiograma de 12 derivações","controle de frequência ou ritmo e avaliação de anticoagulação conforme risco","acidente vascular cerebral cardioembólico","idade avançada, hipertensão e doença estrutural cardíaca","controle de fatores modificáveis e anticoagulação quando indicada","reavaliar sintomas, frequência, adesão e riscos trombótico e hemorrágico"),
  p("car-04","Cardiologia","Doença isquêmica","Síndrome coronariana aguda com supra de ST","dor torácica prolongada, sudorese e supra persistente de ST","dor isquêmica com alteração eletrocardiográfica territorial","ECG imediato e troponina sem atrasar reperfusão","reperfusão imediata por angioplastia primária ou fibrinólise quando apropriada","choque cardiogênico e arritmias ventriculares","tabagismo, diabetes, dislipidemia e hipertensão","cessar tabagismo e controlar fatores de risco","prevenção secundária, reabilitação e monitoramento da função ventricular"),
  p("car-05","Cardiologia","Pericárdio","Pericardite aguda","dor pleurítica que melhora ao sentar e inclinar o tronco para frente","atrito pericárdico e supra difuso de ST com depressão de PR","avaliação clínica, ECG, marcadores e ecocardiograma para derrame","anti-inflamatório associado a colchicina nos casos idiopáticos sem contraindicação","tamponamento cardíaco","infecção viral recente, autoimunidade ou pós-infarto","tratar a causa e evitar esforço durante atividade inflamatória","acompanhar sintomas, proteína C reativa e sinais de derrame"),

  p("pne-01","Pneumologia","Asma","Asma","episódios variáveis de sibilância, dispneia e tosse, piores à noite","variabilidade dos sintomas e do fluxo expiratório","espirometria com resposta broncodilatadora ou demonstração de variabilidade","estratégia contendo corticosteroide inalatório","exacerbação grave e remodelamento de vias aéreas","atopia, história familiar e exposição ocupacional","evitar gatilhos relevantes e não fumar","avaliar controle, técnica inalatória, adesão e exacerbações"),
  p("pne-02","Pneumologia","DPOC","Doença pulmonar obstrutiva crônica","tabagista com dispneia progressiva e tosse crônica","obstrução persistente ao fluxo aéreo","espirometria pós-broncodilatador","broncodilatadores de longa ação, reabilitação e medidas não farmacológicas conforme sintomas","insuficiência respiratória e cor pulmonale","tabagismo e exposição à biomassa","cessação do tabagismo e vacinação indicada","reavaliar sintomas, exacerbações, técnica inalatória e função pulmonar"),
  p("pne-03","Pneumologia","Infecções respiratórias","Pneumonia adquirida na comunidade","febre, tosse, dor pleurítica e novo infiltrado pulmonar","crepitações focais associadas a opacidade nova","radiografia de tórax, quando indicada, associada à avaliação clínica","antibioticoterapia empírica definida por gravidade, comorbidades e epidemiologia","sepse e derrame parapneumônico complicado","idade avançada, tabagismo e doença pulmonar crônica","vacinação e redução de tabagismo/aspiração","reavaliar resposta clínica e investigar ausência de melhora"),
  p("pne-04","Pneumologia","Tromboembolismo","Embolia pulmonar","dispneia súbita, dor pleurítica e taquicardia após imobilização","início agudo com fatores de risco tromboembólicos","estratégia guiada por probabilidade clínica, dímero-D e angiotomografia","anticoagulação; reperfusão se alto risco com instabilidade e sem contraindicação","choque obstrutivo e hipertensão pulmonar tromboembólica crônica","cirurgia, câncer, imobilização e trombofilia","profilaxia adequada em pacientes de risco","definir duração da anticoagulação e vigiar sangramento e dispneia persistente"),
  p("pne-05","Pneumologia","Pleura","Pneumotórax hipertensivo","trauma com dispneia intensa, hipotensão e murmúrio vesicular abolido unilateral","instabilidade com hiperinsuflação unilateral e possível desvio traqueal","diagnóstico clínico, sem aguardar imagem no paciente instável","descompressão imediata seguida de drenagem torácica","parada por choque obstrutivo","trauma, ventilação positiva e doença pulmonar bolhosa","ventilação protetora e manejo da doença pulmonar quando aplicável","confirmar expansão pulmonar e tratar fuga aérea persistente"),

  p("neu-01","Neurologia","Doença cerebrovascular","Acidente vascular cerebral isquêmico","déficit neurológico focal súbito sem hemorragia na tomografia inicial","início abrupto de déficit localizado em território vascular","tomografia sem contraste seguida de imagem vascular conforme protocolo","reperfusão intravenosa e/ou trombectomia em pacientes elegíveis","edema cerebral, transformação hemorrágica e incapacidade","hipertensão, fibrilação atrial, diabetes e tabagismo","controle de fatores de risco e antitrombótico conforme etiologia","reabilitação e investigação etiológica para prevenção secundária"),
  p("neu-02","Neurologia","Epilepsia","Estado de mal epiléptico convulsivo","crise tônico-clônica com cinco minutos ou crises repetidas sem recuperação","atividade convulsiva prolongada com risco de lesão sistêmica","diagnóstico clínico imediato, com glicemia e investigação causal paralela","benzodiazepínico seguido de fármaco de segunda linha se persistir","hipóxia, rabdomiólise e lesão neuronal","baixa adesão, distúrbio metabólico, infecção ou lesão estrutural","adesão ao tratamento e controle da causa precipitante","monitorar recorrência e considerar EEG contínuo se consciência não retorna"),
  p("neu-03","Neurologia","Cefaleias","Hemorragia subaracnóidea","cefaleia em trovoada, vômitos e rigidez de nuca","pior cefaleia da vida com início máximo em segundos","tomografia sem contraste; punção lombar ou angioimagem conforme tempo e resultado","estabilização, nimodipino e tratamento definitivo do aneurisma","ressangramento, vasoespasmo e hidrocefalia","aneurisma intracraniano, tabagismo e hipertensão","cessar tabagismo e controlar pressão; rastrear apenas grupos selecionados","monitorar vasoespasmo, sódio e complicações neurológicas"),
  p("neu-04","Neurologia","Doenças desmielinizantes","Esclerose múltipla","adulto jovem com episódios neurológicos separados no tempo e espaço","neurite óptica, mielite parcial ou síndrome de tronco com remissões","ressonância de encéfalo/medula e critérios de disseminação, com líquor quando necessário","corticoide na crise incapacitante e terapia modificadora para reduzir atividade","incapacidade acumulada e disfunção urinária","sexo feminino, predisposição genética e fatores ambientais","não há prevenção específica; evitar tabagismo e corrigir deficiência quando indicada","monitorar atividade clínica, ressonância e segurança da terapia"),
  p("neu-05","Neurologia","Neurodegeneração","Doença de Parkinson","bradicinesia, rigidez e tremor de repouso assimétrico","bradicinesia associada a rigidez ou tremor de repouso","diagnóstico clínico, reservando imagem para apresentações atípicas","levodopa ou outros agentes conforme impacto funcional e perfil do paciente","quedas, demência, disfagia e flutuações motoras","idade, predisposição genética e exposições selecionadas","atividade física e segurança, sem prevenção farmacológica comprovada","acompanhar resposta, sintomas não motores e complicações do tratamento"),

  p("inf-01","Infectologia","Tuberculose","Tuberculose pulmonar","tosse persistente, emagrecimento, sudorese noturna e cavitação apical","sintomas constitucionais com comprometimento pulmonar crônico","teste rápido molecular e investigação bacteriológica","esquema combinado conforme protocolo e perfil de resistência","hemoptise, disseminação e resistência medicamentosa","contato domiciliar, imunossupressão e ambientes fechados","identificação de contatos, ventilação e tratamento da infecção latente quando indicado","monitorar adesão, toxicidade e resposta bacteriológica"),
  p("inf-02","Infectologia","HIV","Infecção pelo HIV","exposição de risco ou infecção oportunista com testes reagentes","imunodeficiência progressiva associada a replicação viral","algoritmo diagnóstico com testes sequenciais e carga viral para acompanhamento","terapia antirretroviral combinada para todas as pessoas diagnosticadas","infecções oportunistas, neoplasias e doença cardiovascular","relações sem barreira, compartilhamento de material perfurocortante e transmissão vertical","preservativos, PrEP/PEP e supressão viral","acompanhar carga viral, CD4, adesão, interações e comorbidades"),
  p("inf-03","Infectologia","Sistema nervoso central","Meningite bacteriana","febre, cefaleia, rigidez de nuca e alteração mental","síndrome meníngea aguda com toxicidade sistêmica","hemoculturas e líquor quando seguro, sem atrasar antibiótico","antibiótico empírico precoce e dexametasona em cenários indicados","choque, perda auditiva, convulsões e hipertensão intracraniana","extremos de idade, imunossupressão e ausência de vacinação","vacinação e quimioprofilaxia de contatos quando indicada","avaliar sequelas neurológicas e auditivas"),
  p("inf-04","Infectologia","Infecções urinárias","Pielonefrite aguda","febre, dor lombar, náusea e sintomas urinários","dor à punho-percussão lombar com sinais sistêmicos","urina tipo I e urocultura, especialmente em casos complicados","antibiótico com penetração renal definido por gravidade e resistência local","abscesso, sepse e cicatriz renal em grupos vulneráveis","obstrução, gestação, diabetes e instrumentação urinária","corrigir fatores anatômicos e evitar antibiótico desnecessário","reavaliar em 48–72 horas e investigar complicação se não houver melhora"),
  p("inf-05","Infectologia","Infecções de pele","Celulite não purulenta","eritema quente, doloroso e mal delimitado sem coleção","inflamação difusa de derme profunda e subcutâneo","diagnóstico clínico; imagem se suspeita de abscesso profundo","antibiótico dirigido principalmente a estreptococos, ajustado ao contexto","abscesso, fasceíte e bacteremia","linfedema, micose interdigital, trauma e insuficiência venosa","cuidar da barreira cutânea e tratar portas de entrada","confirmar redução da área e rever diagnóstico se progressão rápida"),

  p("end-01","Endocrinologia","Diabetes","Cetoacidose diabética","hiperglicemia, cetose, acidose e desidratação","respiração de Kussmaul e ânion gap aumentado","glicemia, eletrólitos, gasometria/cetonemia e busca do precipitante","cristaloide, insulina e reposição guiada de potássio","edema cerebral, hipocalemia e choque","omissão de insulina, infecção e diabetes novo","educação para dias de doença e acesso contínuo à insulina","monitorar glicose, potássio, ânion gap e resolução da cetose"),
  p("end-02","Endocrinologia","Tireoide","Doença de Graves","perda ponderal, tremor, bócio difuso e oftalmopatia","hipertireoidismo com anticorpo contra receptor de TSH e sinais extratireoidianos","TSH suprimido, T4 livre elevado e anticorpos quando necessários","antitireoidiano, radioiodo ou cirurgia conforme perfil; betabloqueador para sintomas","tempestade tireotóxica, arritmia e perda óssea","sexo feminino, autoimunidade e tabagismo para orbitopatia","cessar tabagismo e uso seguro de iodo/medicamentos","monitorar função tireoidiana, efeitos adversos e orbitopatia"),
  p("end-03","Endocrinologia","Adrenal","Insuficiência adrenal primária","fadiga, perda de peso, hipotensão, hiponatremia, hipercalemia e hiperpigmentação","ACTH elevado com cortisol inadequadamente baixo","cortisol matinal e teste de estímulo com ACTH quando estável","reposição de glicocorticoide e mineralocorticoide; hidrocortisona IV na crise","choque adrenal e distúrbios eletrolíticos","autoimunidade, tuberculose e hemorragia adrenal","educação sobre dose de estresse e cartão de emergência","monitorar sintomas, pressão, eletrólitos e sinais de excesso de reposição"),
  p("end-04","Endocrinologia","Hipófise","Acromegalia","aumento de mãos e pés, prognatismo, sudorese e apneia","crescimento acral progressivo por excesso de GH","IGF-1 e teste de supressão de GH, seguidos de ressonância hipofisária","cirurgia transesfenoidal quando adenoma ressecável","cardiomiopatia, diabetes, apneia e artropatia","adenoma hipofisário produtor de GH","não há prevenção específica","acompanhar IGF-1, função hipofisária e comorbidades"),
  p("end-05","Endocrinologia","Metabolismo ósseo","Hiperparatireoidismo primário","hipercalcemia com PTH inapropriadamente elevado","cálcio alto, fósforo baixo e PTH não suprimido","cálcio corrigido/ionizado, PTH, função renal e avaliação óssea/renal","paratireoidectomia quando critérios clínicos ou laboratoriais são preenchidos","nefrolitíase, osteoporose e doença renal","adenoma de paratireoide e síndromes hereditárias raras","hidratação adequada e evitar fatores agravantes da hipercalcemia","monitorar cálcio, rim e densidade óssea se manejo conservador"),

  p("gas-01","Gastroenterologia","Doença ulcerosa","Úlcera péptica por Helicobacter pylori","dor epigástrica ou sangramento digestivo com infecção por H. pylori","lesão mucosa gastroduodenal associada à bactéria","teste respiratório, antígeno fecal ou biópsia conforme contexto","terapia erradicadora conforme resistência e protocolos locais","hemorragia, perfuração e obstrução","H. pylori e anti-inflamatórios não esteroides","evitar AINE desnecessário e erradicar a bactéria quando indicada","confirmar erradicação com teste apropriado após o tratamento"),
  p("gas-02","Gastroenterologia","Hepatologia","Cirrose descompensada com ascite","doença hepática crônica com ascite, circulação colateral e esplenomegalia","hipertensão portal e redução da função sintética","ultrassom, exames hepáticos e paracentese diagnóstica em ascite nova ou internada","restrição moderada de sódio, diuréticos e manejo da causa; paracentese com albumina quando indicada","peritonite bacteriana espontânea, sangramento varicoso e encefalopatia","álcool, hepatites virais e doença metabólica","vacinação, evitar álcool e tratar a etiologia","rastrear carcinoma hepatocelular e varizes e monitorar descompensações"),
  p("gas-03","Gastroenterologia","Pâncreas","Pancreatite aguda","dor epigástrica intensa irradiada para dorso com lipase elevada","dor típica associada a elevação enzimática ou imagem compatível","lipase e ultrassom para etiologia biliar; tomografia se dúvida ou complicação","cristaloide guiado, analgesia e alimentação enteral precoce conforme tolerância","necrose infectada, coleções e falência orgânica","cálculos biliares, álcool e hipertrigliceridemia","tratar colelitíase/álcool e fatores metabólicos","avaliar gravidade, tolerância alimentar e complicações locais"),
  p("gas-04","Gastroenterologia","Doença inflamatória intestinal","Doença de Crohn","diarreia crônica, dor abdominal, perda ponderal e doença perianal","inflamação transmural descontínua que pode acometer qualquer segmento","ileocolonoscopia com biópsias e imagem do intestino delgado","indução e manutenção conforme gravidade com terapia anti-inflamatória/imunomoduladora","fístulas, estenoses, abscessos e desnutrição","tabagismo e predisposição familiar","cessar tabagismo, vacinação e cuidado nutricional","monitorar remissão clínica e objetiva e rastrear complicações"),
  p("gas-05","Gastroenterologia","Vias biliares","Colangite aguda","febre, icterícia e dor em hipocôndrio direito com obstrução biliar","tríade de Charcot; hipotensão e confusão indicam gravidade","exames hepáticos e ultrassom, com imagem complementar conforme necessidade","antibiótico, suporte e drenagem biliar urgente nos casos moderados/graves","choque séptico e abscesso hepático","coledocolitíase, estenose e instrumentação biliar","tratar a causa da obstrução","confirmar descompressão e resolução clínica/laboratorial"),

  p("nef-01","Nefrologia","Injúria renal aguda","Necrose tubular aguda","aumento de creatinina após choque ou nefrotoxina, com sedimento granular","cilindros granulosos castanhos e perda da capacidade de concentração","creatinina seriada, diurese, sedimento e avaliação da causa","corrigir hipoperfusão, suspender nefrotóxicos e oferecer suporte","hipercalemia, acidose e sobrecarga volêmica","sepse, choque, contraste e fármacos nefrotóxicos","prevenir hipotensão e exposição nefrotóxica evitável","monitorar recuperação renal, volume e eletrólitos"),
  p("nef-02","Nefrologia","Glomerulopatias","Síndrome nefrótica","proteinúria acentuada, hipoalbuminemia, edema e hiperlipidemia","proteinúria em faixa nefrótica com edema generalizado","quantificação de proteína, função renal e investigação etiológica, com biópsia quando indicada","controle de edema e pressão, bloqueio do sistema renina-angiotensina e tratamento da causa","trombose, infecção e desnutrição proteica","diabetes, doenças glomerulares e fármacos","controle metabólico e da doença de base","monitorar proteinúria, função renal e eventos trombóticos"),
  p("nef-03","Nefrologia","Eletrólitos","Hipercalemia","potássio elevado com fraqueza e ondas T apiculadas ou QRS largo","alterações eletrocardiográficas potencialmente fatais","repetir amostra se suspeita de hemólise e realizar ECG imediato","cálcio IV se alteração elétrica, insulina com glicose e remoção de potássio","fibrilação ventricular e assistolia","doença renal, bloqueadores do SRAA e lise celular","revisar medicamentos e orientar dieta apenas quando apropriado","recontrolar potássio e investigar rebote"),
  p("nef-04","Nefrologia","Distúrbios ácido-base","Acidose metabólica com ânion gap elevado","pH baixo, bicarbonato reduzido e aumento de ânions não medidos","compensação respiratória previsível pela fórmula de Winter","gasometria, eletrólitos, lactato, cetonas e investigação de toxinas","tratar a causa, oferecendo suporte e antídoto/diálise quando indicado","arritmia, choque e depressão miocárdica","cetoacidose, lactato, insuficiência renal e intoxicações","controle das doenças predisponentes e uso seguro de fármacos","seguir pH, bicarbonato, ânion gap e causa subjacente"),
  p("nef-05","Nefrologia","Doença renal crônica","Doença renal crônica","alteração estrutural renal ou TFG reduzida persistente por pelo menos três meses","classificação combinada por TFG e albuminúria","creatinina/TFG, relação albumina-creatinina e avaliação etiológica","controle pressórico, bloqueio do SRAA e inibidor de SGLT2 quando indicados","doença cardiovascular, anemia e distúrbio mineral ósseo","diabetes, hipertensão e glomerulopatias","controle metabólico e evitar nefrotóxicos","monitorar TFG, albuminúria, potássio e complicações"),

  p("reu-01","Reumatologia","Artrites","Artrite reumatoide","poliartrite simétrica de pequenas articulações com rigidez matinal prolongada","sinovite persistente de metacarpofalângicas e interfalângicas proximais","avaliação clínica, fator reumatoide, anti-CCP e imagem basal","DMARD precoce, frequentemente metotrexato quando apropriado","erosões, deformidades e doença cardiovascular","tabagismo, sexo feminino e predisposição genética","cessar tabagismo; não há prevenção específica estabelecida","estratégia treat-to-target com avaliação de atividade e toxicidade"),
  p("reu-02","Reumatologia","Conectivopatias","Lúpus eritematoso sistêmico","mulher jovem com artralgia, fotossensibilidade, citopenia e proteinúria","doença autoimune multissistêmica com autoanticorpos","ANA como teste sensível, seguido de anticorpos específicos, complemento e avaliação de órgãos","hidroxicloroquina para a maioria e imunossupressão conforme órgão e gravidade","nefrite, trombose, infecção e dano cardiovascular","sexo feminino e predisposição genética/hormonal","fotoproteção, vacinação e controle cardiovascular","monitorar atividade, urina, função renal, complemento e toxicidade ocular"),
  p("reu-03","Reumatologia","Artrites por cristais","Gota","monoartrite muito dolorosa de início súbito, frequentemente na primeira metatarsofalângica","cristais de urato em agulha com birrefringência negativa","artrocentese quando diagnóstico incerto ou infecção precisa ser excluída","anti-inflamatório, colchicina ou corticoide na crise; redução de urato quando indicada","tofos, nefrolitíase e dano articular","doença renal, diuréticos, álcool e síndrome metabólica","reduzir álcool excessivo e fatores metabólicos; não restringir de forma extrema","monitorar urato sérico e titular terapia à meta"),
  p("reu-04","Reumatologia","Vasculites","Arterite de células gigantes","pessoa acima de 50 anos com cefaleia nova, claudicação de mandíbula e alteração visual","inflamação de grandes/médias artérias com risco de cegueira","VHS/PCR, ultrassom ou biópsia temporal sem atrasar tratamento","glicocorticoide imediato, intravenoso se ameaça visual","perda visual irreversível e aneurisma de aorta","idade avançada e associação com polimialgia reumática","não há prevenção específica","monitorar sintomas, inflamação e complicações aórticas"),
  p("reu-05","Reumatologia","Espondiloartrites","Espondilite anquilosante","adulto jovem com dor lombar inflamatória que melhora com exercício","sacroileíte e limitação progressiva da mobilidade axial","radiografia ou ressonância de sacroilíacas conforme estágio","exercício/fisioterapia e anti-inflamatório; biológico se atividade persistente","anquilose, uveíte e doença cardiovascular","HLA-B27, história familiar e tabagismo","não fumar e manter atividade física","avaliar atividade, mobilidade, uveíte e resposta terapêutica"),

  p("ped-01","Pediatria","Infecções respiratórias","Bronquiolite viral","lactente com coriza seguida de tosse, sibilância e esforço respiratório","primeiro episódio de sibilância em lactente durante infecção viral","diagnóstico clínico; exames não são rotineiros na apresentação típica","suporte, higiene nasal, hidratação e oxigênio se necessário","apneia, desidratação e insuficiência respiratória","prematuridade, cardiopatia e pouca idade","higiene das mãos e redução de exposição; imunoprofilaxia em grupos indicados","reavaliar alimentação, esforço respiratório e oxigenação"),
  p("ped-02","Pediatria","Neurologia pediátrica","Convulsão febril simples","criança de 6 meses a 5 anos com crise generalizada menor que 15 minutos, única em 24 horas","crise generalizada breve associada à febre sem infecção do SNC","diagnóstico clínico; punção lombar apenas quando há suspeita de meningite","suporte e benzodiazepínico se crise durar cinco minutos ou mais","recorrência; pequeno aumento do risco posterior de epilepsia","idade baixa na primeira crise e história familiar","orientação familiar e segurança; antiepiléptico contínuo não é rotina","acompanhar desenvolvimento e investigar características complexas"),
  p("ped-03","Pediatria","Gastroenterologia","Gastroenterite aguda com alguma desidratação","diarreia com sede, olhos fundos e prega cutânea de retorno lento","dois ou mais sinais clínicos de alguma desidratação","avaliação clínica do estado de hidratação","solução de reidratação oral supervisionada e manutenção da alimentação","choque hipovolêmico e distúrbios eletrolíticos","baixa idade, perdas intensas e dificuldade de acesso a líquidos","água segura, saneamento, higiene e vacinação contra rotavírus","reavaliar sinais após reidratação e orientar sinais de alarme"),
  p("ped-04","Pediatria","Exantemas","Sarampo","febre alta, tosse, coriza, conjuntivite e exantema craniocaudal","manchas de Koplik antes do exantema","RT-PCR/sorologia conforme vigilância, com notificação imediata","suporte e vitamina A conforme protocolo","pneumonia, encefalite e panencefalite tardia","ausência de vacinação e contato com caso","vacinação tríplice viral","acompanhar complicações e realizar bloqueio/controle de contatos"),
  p("ped-05","Pediatria","Crescimento e desenvolvimento","Falha de crescimento","queda sustentada do peso ou cruzamento de canais de crescimento","trajetória inadequada, mais informativa que medida isolada","antropometria seriada e avaliação alimentar, clínica e psicossocial","tratar causa e garantir aporte nutricional seguro","déficit de desenvolvimento e imunidade comprometida","prematuridade, doença crônica, insegurança alimentar e dificuldade alimentar","acompanhamento regular e apoio à alimentação adequada","monitorar velocidade de crescimento e desenvolvimento"),

  p("obs-01","Obstetrícia","Hipertensão na gestação","Pré-eclâmpsia com sinais de gravidade","hipertensão após 20 semanas com cefaleia, alteração visual ou disfunção orgânica","hipertensão gestacional associada a lesão de órgão-alvo, mesmo sem proteinúria","pressão confirmada, proteinúria e avaliação hematológica, renal, hepática e fetal","sulfato de magnésio quando indicado, controle pressórico e resolução conforme idade/gravidade","eclâmpsia, HELLP, descolamento placentário e restrição fetal","história prévia, gestação múltipla, doença renal e hipertensão crônica","AAS em baixa dose e cálcio em gestantes elegíveis conforme protocolo","vigiar mãe e feto e reavaliar risco cardiovascular no pós-parto"),
  p("obs-02","Obstetrícia","Hemorragias","Descolamento prematuro de placenta","sangramento vaginal doloroso, hipertonia uterina e sofrimento fetal","dor e útero hipertônico com sangramento que pode ser oculto","diagnóstico clínico apoiado por ultrassom, que não exclui o quadro","estabilização e resolução imediata conforme condição materno-fetal","choque, coagulopatia e óbito fetal","hipertensão, trauma, cocaína e descolamento prévio","controle pressórico e evitar tabaco/drogas","monitorar hemorragia, coagulação e recuperação materna"),
  p("obs-03","Obstetrícia","Diabetes gestacional","Diabetes mellitus gestacional","hiperglicemia diagnosticada durante a gestação sem critérios de diabetes manifesto","intolerância à glicose associada à resistência insulínica gestacional","rastreamento/diagnóstico glicêmico conforme protocolo pré-natal","plano alimentar, atividade segura, monitorização e insulina se metas não forem atingidas","macrossomia, distocia de ombro, pré-eclâmpsia e hipoglicemia neonatal","obesidade, idade, história familiar e diabetes gestacional prévio","peso saudável e planejamento pré-concepcional","reclassificar glicemia no pós-parto e rastrear diabetes periodicamente"),
  p("obs-04","Obstetrícia","Trabalho de parto","Hemorragia pós-parto por atonia uterina","sangramento volumoso após o parto com útero aumentado e amolecido","falha de contração uterina, a causa mais comum de hemorragia pós-parto","diagnóstico clínico com busca simultânea dos quatro Ts","massagem uterina, ocitocina, ressuscitação e escalonamento rápido","choque, coagulopatia e lesão orgânica","sobredistensão, trabalho prolongado e corioamnionite","manejo ativo do terceiro período e identificação de risco","monitorar sangramento, hemoglobina e recuperação física/psicológica"),
  p("obs-05","Obstetrícia","Urgências obstétricas","Gravidez ectópica rota","atraso menstrual, dor pélvica, sangramento e instabilidade hemodinâmica","gestação fora da cavidade uterina com hemoperitônio","beta-hCG e ultrassom transvaginal sem atrasar cirurgia na instabilidade","tratamento cirúrgico urgente e ressuscitação","choque hemorrágico e perda tubária","ectópica prévia, doença tubária e reprodução assistida","redução de IST e tabagismo; não há prevenção completa","orientar risco futuro e avaliação precoce em nova gestação"),

  p("gin-01","Ginecologia","Endocrinologia ginecológica","Síndrome dos ovários policísticos","oligomenorreia, hiperandrogenismo e exclusão de outras causas","disfunção ovulatória e hiperandrogenismo clínico ou laboratorial","avaliação clínica/hormonal para excluir diagnósticos alternativos; ultrassom quando necessário","mudança de estilo de vida, contraceptivo combinado ou indutor de ovulação conforme objetivo","hiperplasia endometrial, infertilidade e risco metabólico","obesidade e predisposição familiar","peso saudável e proteção endometrial quando anovulação persistente","acompanhar ciclos, metabolismo e objetivos reprodutivos"),
  p("gin-02","Ginecologia","Dor pélvica","Endometriose","dismenorreia progressiva, dispareunia profunda e infertilidade","dor cíclica com possível endometrioma ou lesões profundas","diagnóstico clínico apoiado por ultrassom especializado; laparoscopia em situações selecionadas","supressão hormonal ou cirurgia conforme sintomas, desejo reprodutivo e anatomia","dor crônica, infertilidade e comprometimento intestinal/urinário","menarca precoce, ciclos curtos e história familiar","não há prevenção comprovada","reavaliar dor, função, fertilidade e efeitos do tratamento"),
  p("gin-03","Ginecologia","Infecções","Doença inflamatória pélvica","dor pélvica, corrimento e dor à mobilização do colo","diagnóstico clínico com baixo limiar para tratamento","testes para IST, gravidez e ultrassom se abscesso ou diagnóstico incerto","antibiótico empírico cobrindo gonococo, clamídia e anaeróbios","infertilidade tubária, ectópica e dor crônica","IST, múltiplas parcerias e episódio prévio","preservativo, rastreamento e tratamento de parceiros","reavaliar resposta em 48–72 horas"),
  p("gin-04","Ginecologia","Oncologia ginecológica","Câncer do colo do útero","sangramento pós-coital ou lesão cervical em pessoa sem rastreamento adequado","neoplasia fortemente associada a HPV oncogênico persistente","citologia/teste de HPV no rastreamento e colposcopia/biópsia na alteração","tratamento conforme estágio com cirurgia, radioterapia e/ou quimioterapia","invasão local, hidronefrose e metástases","HPV persistente, tabagismo e imunossupressão","vacinação contra HPV e rastreamento organizado","seguimento oncológico e vigilância de recorrência"),
  p("gin-05","Ginecologia","Climatério","Síndrome geniturinária da menopausa","secura vaginal, dispareunia e sintomas urinários após menopausa","atrofia vulvovaginal por hipoestrogenismo","diagnóstico clínico e exame ginecológico, excluindo outras causas","hidratantes/lubrificantes e estrogênio vaginal quando indicado e seguro","fissuras, dor sexual e infecções urinárias recorrentes","menopausa, lactação e terapias antiestrogênicas","atividade sexual confortável e cuidado local, sem prevenção total","reavaliar sintomas e qualquer sangramento pós-menopausa"),

  p("psi-01","Psiquiatria","Transtornos do humor","Transtorno depressivo maior","humor deprimido ou anedonia por pelo menos duas semanas com prejuízo funcional","sintomas afetivos, cognitivos e somáticos persistentes","entrevista clínica, avaliação de risco suicida e exclusão de causas/mania","psicoterapia e/ou antidepressivo conforme gravidade e preferência","suicídio, recorrência e incapacidade","episódio prévio, história familiar, trauma e doença crônica","apoio psicossocial, sono e tratamento precoce; prevenção total não é possível","reavaliar risco, adesão, resposta e sintomas de mania"),
  p("psi-02","Psiquiatria","Transtornos psicóticos","Esquizofrenia","delírios, alucinações e desorganização com prejuízo persistente","sintomas positivos e negativos com declínio funcional","diagnóstico clínico após excluir substâncias, humor e causas orgânicas","antipsicótico associado a intervenções psicossociais","suicídio, síndrome metabólica e prejuízo social","história familiar, complicações perinatais e cannabis em vulneráveis","reduzir uso de substâncias e intervir precocemente","monitorar sintomas, função, adesão e efeitos metabólicos/motores"),
  p("psi-03","Psiquiatria","Transtornos cognitivos","Delirium","início agudo de desatenção e consciência flutuante em paciente clínico","curso flutuante e desatenção","avaliação clínica estruturada e busca ativa de causas","tratar a causa, reorientar, mobilizar e corrigir fatores ambientais","quedas, aspiração, internação prolongada e mortalidade","idade, demência, infecção, fármacos e privação sensorial","evitar polifarmácia, imobilidade, desidratação e distúrbio do sono","acompanhar resolução e investigar déficit cognitivo persistente"),
  p("psi-04","Psiquiatria","Transtornos ansiosos","Transtorno de pânico","ataques súbitos recorrentes de medo intenso com preocupação persistente","picos abruptos com sintomas autonômicos e medo de morrer/perder controle","diagnóstico clínico após excluir causas cardiopulmonares, endócrinas e substâncias","terapia cognitivo-comportamental e antidepressivo quando indicado","agorafobia, depressão e uso inadequado de emergência","história familiar, estresse e outros transtornos ansiosos","manejo de estresse e tratamento precoce","acompanhar frequência, evitação e uso de benzodiazepínicos"),
  p("psi-05","Psiquiatria","Dependência química","Síndrome de abstinência alcoólica grave","tremor, sudorese e agitação após cessar álcool, evoluindo com confusão e alucinações","hiperatividade autonômica após redução abrupta do consumo","diagnóstico clínico e avaliação de glicose, eletrólitos e comorbidades","benzodiazepínico, tiamina antes de glicose quando possível e suporte","convulsões, delirium tremens e arritmias","dependência intensa, abstinência prévia grave e doença clínica","tratamento longitudinal do transtorno por uso de álcool","monitorar gravidade, nutrição e vinculação ao cuidado após estabilização"),

  p("cir-01","Cirurgia Geral","Abdome agudo","Apendicite aguda","dor periumbilical migrando para fossa ilíaca direita, anorexia e náusea","dor localizada em ponto de McBurney com sinais inflamatórios","avaliação clínica e ultrassom/TC conforme idade, sexo e incerteza","apendicectomia e antibiótico; manejo não operatório apenas em selecionados","perfuração, abscesso e peritonite","obstrução luminal, sem fator modificável claro","não há prevenção específica","reavaliar ferida, infecção e anatomopatológico"),
  p("cir-02","Cirurgia Geral","Vias biliares","Colecistite aguda","dor persistente em hipocôndrio direito, febre e Murphy positivo","inflamação da vesícula geralmente por cálculo impactado","ultrassom de abdome","analgesia, antibiótico quando indicado e colecistectomia precoce","empiema, gangrena e perfuração","colelitíase, obesidade, sexo feminino e idade","peso saudável, sem indicação de retirar cálculo assintomático rotineiramente","acompanhar recuperação e complicações biliares"),
  p("cir-03","Cirurgia Geral","Obstrução intestinal","Obstrução de intestino delgado","dor em cólica, vômitos, distensão e parada de eliminação de gases","níveis hidroaéreos e dilatação proximal com ponto de transição","tomografia com contraste quando estável e diagnóstico não evidente","descompressão, fluidos e cirurgia se isquemia, estrangulamento ou falha","necrose, perfuração e sepse","aderências pós-operatórias e hérnias","técnica cirúrgica cuidadosa e correção eletiva de hérnia quando indicada","monitorar dor, diurese, eletrólitos e sinais de isquemia"),
  p("cir-04","Cirurgia Geral","Hérnias","Hérnia inguinal estrangulada","massa inguinal dolorosa, irredutível, com vômitos e sinais sistêmicos","comprometimento vascular do conteúdo herniário","diagnóstico clínico; imagem apenas se dúvida e sem atrasar cirurgia","operação urgente e ressuscitação","necrose intestinal, perfuração e sepse","sexo masculino, idade, esforço crônico e hérnia prévia","correção eletiva da hérnia sintomática antes de complicar","avaliar ferida, recorrência e retorno gradual ao esforço"),
  p("cir-05","Cirurgia Geral","Pós-operatório","Infecção de sítio cirúrgico","dor, eritema, calor e secreção purulenta na incisão após operação","sinais inflamatórios locais com ou sem deiscência","diagnóstico clínico; cultura de material profundo quando apropriada","abrir/drenar quando coleção e usar antibiótico se celulite ou sinais sistêmicos","deiscência, abscesso profundo e sepse","diabetes, obesidade, tabagismo e operação contaminada","antibioticoprofilaxia correta, preparo adequado e controle glicêmico","acompanhar cicatrização e sinais de infecção profunda"),

  p("eme-01","Urgência e Emergência","Reanimação","Fibrilação ventricular em parada cardíaca","paciente inconsciente, sem pulso, com ritmo caótico sem QRS organizado","ritmo chocável durante parada","monitor cardíaco/desfibrilador sem interromper compressões","desfibrilação e retomada imediata de RCP de alta qualidade","lesão cerebral hipóxico-isquêmica e recorrência da arritmia","infarto, cardiomiopatia e distúrbio eletrolítico","tratar cardiopatia e fatores reversíveis","cuidado pós-parada com controle de temperatura, hemodinâmica e causa"),
  p("eme-02","Urgência e Emergência","Choque","Choque séptico","infecção com hipotensão persistente apesar de fluidos e necessidade de vasopressor","vasodilatação, disfunção orgânica e lactato possivelmente elevado","culturas, lactato e busca do foco sem atrasar antibiótico","antibiótico precoce, cristaloide guiado e noradrenalina se necessário","falência de múltiplos órgãos","infecção grave, imunossupressão e atraso no controle do foco","prevenção de infecções e reconhecimento precoce","monitorar perfusão, diurese, lactato e controle do foco"),
  p("eme-03","Urgência e Emergência","Alergia","Anafilaxia","início súbito de urticária, broncoespasmo e hipotensão após exposição","comprometimento respiratório ou circulatório agudo com manifestação alérgica","diagnóstico clínico; triptase pode apoiar depois, sem atrasar tratamento","adrenalina intramuscular na coxa, repetida se necessário, e suporte","obstrução de via aérea e choque","exposição prévia a alimento, medicamento, veneno ou látex","evitar gatilho e portar plano/adrenalina autoinjetável quando disponível","observar reação bifásica e encaminhar para investigação"),
  p("eme-04","Urgência e Emergência","Toxicologia","Intoxicação por opioide","depressão de consciência, miose e hipoventilação","tríade de coma, pupilas puntiformes e depressão respiratória","diagnóstico clínico apoiado por resposta à naloxona","ventilação e naloxona titulada","aspiração, edema pulmonar e recorrência após fim do antídoto","uso de opioides, associação com sedativos e dose desconhecida","redução de danos e acesso a naloxona","observar pelo tempo do opioide e vincular ao tratamento"),
  p("eme-05","Urgência e Emergência","Trauma","Choque hemorrágico no trauma","taquicardia, hipotensão, pele fria e alteração mental após trauma","hipoperfusão por perda sanguínea até prova em contrário","avaliação primária, FAST e imagem apenas conforme estabilidade","controle imediato da hemorragia e ressuscitação balanceada","coagulopatia, hipotermia, acidose e morte","trauma de alta energia e uso de anticoagulante","segurança viária e prevenção de violência","monitorar perfusão, coagulopatia e lesões não reconhecidas"),

  p("onc-01","Oncologia","Emergências oncológicas","Neutropenia febril","febre após quimioterapia com neutrófilos muito reduzidos","febre em paciente neutropênico sem esperar foco evidente","hemograma, culturas e avaliação de foco/risco","antibiótico antipseudomonas o mais cedo possível","choque séptico e infecção invasiva","quimioterapia mielossupressora e mucosite","profilaxia com fator estimulador em esquemas de risco selecionados","acompanhar culturas, neutrófilos e resposta clínica"),
  p("onc-02","Oncologia","Emergências oncológicas","Síndrome de lise tumoral","hipercalemia, hiperfosfatemia, hipocalcemia e hiperuricemia após terapia","destruição celular rápida com liberação de conteúdo intracelular","eletrólitos, ácido úrico, creatinina e ECG seriados","hidratação, hipouricemiante e correção urgente dos distúrbios","arritmia, convulsão e injúria renal","neoplasia de alta carga e grande sensibilidade ao tratamento","estratificação de risco, hidratação e profilaxia antes da terapia","monitorização laboratorial frequente durante período de risco"),
  p("onc-03","Oncologia","Emergências oncológicas","Compressão medular metastática","câncer com dor vertebral, fraqueza progressiva e disfunção esfincteriana","déficit neurológico abaixo de lesão vertebral dolorosa","ressonância urgente de toda a coluna relevante","corticoide quando indicado e definição urgente de cirurgia/radioterapia","paraplegia permanente e disfunção vesical","metástases vertebrais de mama, próstata, pulmão e outros tumores","tratamento oncológico e atenção precoce à dor vertebral","acompanhar função neurológica, dor e reabilitação"),
  p("onc-04","Oncologia","Cuidados paliativos","Dor oncológica","dor persistente relacionada ao tumor ou tratamento com impacto funcional","avaliação multidimensional da intensidade, mecanismo e sofrimento","história/exame e imagem apenas quando muda a conduta","analgesia multimodal com opioide para dor moderada/grave, titulada e com prevenção de efeitos adversos","delirium, constipação, sedação e perda funcional","doença avançada, metástase óssea e neuropatia por tratamento","antecipar sintomas e tratar a doença quando possível","reavaliar alívio, função, efeitos adversos e objetivos do paciente"),
  p("onc-05","Oncologia","Rastreamento","Câncer colorretal em população de risco habitual","adulto assintomático na faixa etária recomendada para rastreamento","lesões precursoras detectáveis antes de sintomas","teste fecal periódico ou método estrutural conforme diretriz e preferência","colonoscopia diagnóstica após teste não invasivo positivo","obstrução, sangramento, metástase e anemia","idade, história familiar, doença inflamatória intestinal e síndromes hereditárias","rastreamento apropriado, atividade física, peso saudável e não fumar","garantir colonoscopia após resultado positivo e definir intervalo pelo achado"),

  p("ort-01","Ortopedia","Trauma","Fratura exposta","ferida comunicando-se com foco de fratura após trauma","contaminação óssea e de partes moles","radiografias após avaliação neurovascular; classificação definitiva no desbridamento","antibiótico IV precoce, profilaxia antitetânica, estabilização e desbridamento","osteomielite, não união e síndrome compartimental","trauma de alta energia e contaminação intensa","prevenção de acidentes e proteção ocupacional","monitorar infecção, consolidação e função"),
  p("ort-02","Ortopedia","Urgências","Síndrome compartimental aguda","dor desproporcional e piora ao estiramento passivo após trauma","pressão elevada em compartimento fechado, mesmo com pulso presente","diagnóstico clínico; pressão compartimental se exame não confiável","fasciotomia urgente","necrose muscular, lesão nervosa e insuficiência renal","fratura de tíbia, esmagamento e reperfusão","imobilização sem compressão excessiva e vigilância pós-trauma","acompanhar função, ferida e rabdomiólise"),
  p("ort-03","Ortopedia","Infecções","Artrite séptica","monoartrite aguda, febre e incapacidade de mobilizar","líquido sinovial inflamatório com possível bactéria","artrocentese para contagem, cristais, Gram e cultura","drenagem e antibiótico precoce após culturas","destruição articular e sepse","prótese, idade, imunossupressão e bacteremia","prevenir infecção e técnica asséptica em procedimentos","seguir resposta clínica, PCR e cultura"),
  p("ort-04","Ortopedia","Coluna","Síndrome da cauda equina","lombalgia com anestesia em sela, retenção urinária e fraqueza bilateral","compressão de raízes lombossacrais com disfunção esfincteriana","ressonância lombar urgente","descompressão cirúrgica urgente","disfunção vesical, sexual e motora permanente","hérnia discal volumosa, tumor e abscesso","não há prevenção específica","reabilitação e acompanhamento urológico/neurológico"),
  p("ort-05","Ortopedia","Metabolismo ósseo","Fratura de fragilidade por osteoporose","fratura após trauma de baixa energia em pessoa idosa","redução da resistência óssea, frequentemente vertebral ou de quadril","densitometria e avaliação de causas secundárias sem atrasar tratamento após fratura típica","cálcio/vitamina D quando necessários, exercício e fármaco antiosteoporótico conforme risco","nova fratura, incapacidade e mortalidade","idade, menopausa, corticoide, baixo peso e quedas","exercício resistido, prevenção de quedas e saúde óssea","monitorar adesão, novas fraturas e resposta conforme terapia"),

  p("der-01","Dermatologia","Oncologia cutânea","Melanoma cutâneo","lesão pigmentada assimétrica, irregular, multicolorida e em evolução","mudança progressiva segundo ABCDE ou lesão diferente das demais","dermatoscopia e biópsia excisional com margens estreitas","excisão ampliada e estadiamento conforme espessura","metástase linfonodal e visceral","radiação ultravioleta, pele clara e história familiar","fotoproteção e evitar queimaduras solares","exame cutâneo e seguimento conforme estágio"),
  p("der-02","Dermatologia","Infecções","Hanseníase","mancha com redução de sensibilidade e nervo periférico espessado","alteração sensitiva em lesão cutânea ou comprometimento neural","exame dermatoneurológico e baciloscopia/biópsia quando necessário","poliquimioterapia conforme classificação operacional","neuropatia, deformidade e reações hansênicas","contato prolongado com caso não tratado","diagnóstico precoce, exame de contatos e vacinação conforme protocolo","avaliar função neural e reações durante e após tratamento"),
  p("der-03","Dermatologia","Farmacodermias","Síndrome de Stevens-Johnson/necrólise epidérmica","febre, dor cutânea, bolhas e erosões de mucosas após medicamento","necrose epidérmica com descolamento e acometimento mucoso","diagnóstico clínico e biópsia quando necessária","suspender imediatamente o agente e oferecer suporte especializado","sepse, falência orgânica e sequelas oculares","fármacos de alto risco e alelos HLA específicos em populações","evitar reexposição e registrar alergia grave","seguimento dermatológico e oftalmológico"),
  p("der-04","Dermatologia","Doenças inflamatórias","Psoríase em placas","placas eritematoescamosas bem delimitadas em superfícies extensoras","escamas prateadas e possível alteração ungueal","diagnóstico clínico; biópsia apenas se dúvida","tópicos, fototerapia ou terapia sistêmica conforme extensão e impacto","artrite psoriásica e risco cardiometabólico","história familiar, obesidade, tabagismo e certos fármacos","peso saudável, não fumar e evitar gatilhos pessoais","avaliar pele, articulações, qualidade de vida e comorbidades"),
  p("der-05","Dermatologia","Infecções graves","Fasceíte necrosante","dor intensa desproporcional, edema rapidamente progressivo e toxicidade sistêmica","progressão rápida com comprometimento fascial e possível crepitação","diagnóstico clínico-cirúrgico; imagem não deve atrasar operação","desbridamento imediato e antibiótico de amplo espectro","choque, amputação e morte","diabetes, imunossupressão, trauma e cirurgia","cuidado de feridas e tratamento precoce de infecções","reexplorações seriadas e suporte intensivo"),

  p("oft-01","Oftalmologia","Urgências","Glaucoma agudo de ângulo fechado","dor ocular intensa, halos, náusea e pupila médio-dilatada","pressão intraocular muito elevada com câmara anterior rasa","tonometria e exame oftalmológico sem atrasar tratamento","redução medicamentosa urgente da pressão e iridotomia definitiva","perda visual irreversível","ângulo estreito, hipermetropia e dilatação pupilar","iridotomia profilática no olho de risco conforme avaliação","controlar pressão e avaliar o olho contralateral"),
  p("oft-02","Oftalmologia","Retina","Descolamento de retina","fotopsias, moscas volantes súbitas e cortina no campo visual","perda de campo progressiva sem dor","fundoscopia com dilatação e ultrassom se meios opacos","reparo retiniano urgente conforme tipo e mácula","perda visual permanente","miopia alta, cirurgia de catarata e trauma","avaliação precoce de roturas e proteção ocular","monitorar retina contralateral e recuperação visual"),
  p("oft-03","Oftalmologia","Infecções","Celulite orbitária","febre, edema palpebral, proptose, dor à movimentação e oftalmoplegia","sinais orbitários posteriores ao septo","tomografia de órbitas e seios da face","antibiótico IV e drenagem se abscesso/indicação","abscesso, trombose do seio cavernoso e perda visual","sinusite bacteriana e trauma","tratar sinusite complicada e vacinação apropriada","acompanhar visão, motilidade e resposta sistêmica"),
  p("oft-04","Oftalmologia","Vascular","Oclusão da artéria central da retina","perda visual monocular súbita, profunda e indolor","mácula em cereja e retina pálida","fundoscopia urgente e investigação vascular","avaliação emergencial de AVC e medidas oculares conforme protocolo local","perda visual permanente e futuro AVC","aterosclerose, fibrilação atrial e arterite de células gigantes","controle vascular e tratamento da fonte embólica/inflamatória","investigação etiológica e prevenção secundária"),
  p("oft-05","Oftalmologia","Córnea","Ceratite infecciosa","dor ocular, fotofobia e infiltrado corneano em usuário de lente","defeito epitelial com infiltrado estromal","exame em lâmpada de fenda e cultura em casos graves/atípicos","antimicrobiano tópico intensivo e suspensão da lente","perfuração e cicatriz visual","lente de contato, trauma vegetal e doença da superfície","higiene de lentes e nunca dormir/nadar com elas quando contraindicado","reavaliação oftalmológica precoce até resolução"),

  p("aps-01","Medicina de Família e Comunidade","Atenção primária","Hipertensão arterial na atenção primária","pressão elevada repetidamente em adulto assintomático","elevação persistente confirmada fora de situação aguda","medidas padronizadas repetidas e monitorização fora do consultório quando possível","mudança de estilo de vida e fármacos conforme nível e risco cardiovascular","AVC, infarto, doença renal e insuficiência cardíaca","idade, sal, obesidade, sedentarismo e história familiar","peso saudável, atividade, menos sódio, não fumar","acompanhar pressão, adesão, efeitos e risco global"),
  p("aps-02","Medicina de Família e Comunidade","Prevenção","Rastreamento do câncer do colo do útero","pessoa assintomática na população-alvo com colo uterino","prevenção secundária baseada em detecção de HPV/lesões precursoras","teste recomendado pelo programa vigente, com seguimento do resultado","encaminhamento conforme resultado, não tratamento empírico","sobrediagnóstico se fora da faixa e câncer se falha de seguimento","HPV persistente, tabagismo e imunossupressão","vacinação contra HPV e rastreamento organizado","garantir busca ativa de resultados alterados"),
  p("aps-03","Medicina de Família e Comunidade","Saúde do idoso","Avaliação de risco de quedas","idoso com queda recente, polifarmácia e dificuldade de marcha","risco multifatorial envolvendo equilíbrio, visão, ambiente e medicamentos","história de quedas, teste de marcha/equilíbrio, visão, ortostatismo e revisão medicamentosa","intervenção multifatorial individualizada","fratura, medo de cair e perda de independência","queda prévia, sedativos, fraqueza e hipotensão postural","exercício, ambiente seguro e revisão de fármacos","acompanhar novas quedas e adesão às intervenções"),
  p("aps-04","Medicina de Família e Comunidade","Saúde mental","Risco de suicídio na atenção primária","pessoa com desesperança, plano definido, meios disponíveis e intenção","plano, intenção e acesso ao meio indicam alto risco","perguntas diretas sobre ideação, plano, meios, intenção e proteção","garantir segurança e avaliação urgente sem deixar a pessoa sozinha","tentativa e morte por suicídio","tentativa prévia, transtorno mental, substâncias e crise aguda","restrição de meios, tratamento e plano de segurança","contato próximo após crise e coordenação com saúde mental"),
  p("aps-05","Medicina de Família e Comunidade","Cuidado longitudinal","Multimorbidade e polifarmácia","idoso com várias doenças e muitos medicamentos, tontura e quedas","tratamento centrado em metas da pessoa e carga terapêutica","reconciliação medicamentosa e revisão de indicação, benefício, dano e preferência","desprescrição compartilhada e priorização de tratamentos de maior benefício","interações, eventos adversos e baixa adesão","múltiplos prescritores, fragilidade e transições de cuidado","coordenação, lista atualizada e revisão periódica","monitorar sintomas, função e efeitos após cada mudança"),

  p("car-06","Cardiologia","Endocardite","Endocardite infecciosa","febre persistente, novo sopro e hemoculturas positivas em pessoa com prótese valvar","bacteremia sustentada associada a lesão endocárdica","múltiplos pares de hemoculturas antes do antibiótico e ecocardiograma","antibiótico intravenoso dirigido e avaliação cirúrgica quando há insuficiência, infecção não controlada ou alto risco embólico","insuficiência valvar, abscesso, embolia e bloqueio atrioventricular","prótese valvar, endocardite prévia, dispositivo intracardíaco e uso de droga injetável","higiene bucal e profilaxia apenas nos grupos/procedimentos indicados","repetir culturas até negativação e acompanhar função valvar"),
  p("pne-06","Pneumologia","Medicina do sono","Apneia obstrutiva do sono","ronco alto, pausas respiratórias observadas e sonolência diurna em pessoa com obesidade","colapso recorrente da via aérea superior durante o sono","polissonografia ou estudo domiciliar validado em paciente apropriado","CPAP associado a redução de peso e medidas comportamentais conforme gravidade","hipertensão, arritmia, acidente automobilístico e risco cardiovascular","obesidade, sexo masculino, idade e alterações craniofaciais","peso saudável, evitar álcool/sedativos à noite e tratar obstrução nasal quando pertinente","verificar adesão ao CPAP, sintomas residuais e risco ocupacional"),
  p("neu-06","Neurologia","Junção neuromuscular","Miastenia gravis","ptose e diplopia flutuantes, piorando ao longo do dia, com reflexos preservados","fraqueza fatigável sem déficit sensitivo","anticorpos contra receptor de acetilcolina/MuSK, eletrofisiologia e imagem do timo","inibidor de acetilcolinesterase e imunoterapia conforme gravidade; suporte ventilatório na crise","crise miastênica com insuficiência respiratória e aspiração","timoma, autoimunidade e certos medicamentos agravantes","evitar fármacos precipitantes e tratar infecções precocemente","acompanhar força bulbar/respiratória, atividade e efeitos da imunoterapia"),
  p("inf-06","Infectologia","Arboviroses","Dengue com sinais de alarme","febre em resolução acompanhada de dor abdominal persistente, vômitos, hemoconcentração e queda de plaquetas","extravasamento plasmático na fase crítica, frequentemente perto da defervescência","diagnóstico clínico-epidemiológico com hematócrito seriado e teste virológico/sorológico conforme o dia","hidratação guiada e observação hospitalar, evitando excesso de fluidos e anti-inflamatórios","choque, hemorragia grave e disfunção orgânica","exposição ao Aedes em área de transmissão e infecção prévia por outro sorotipo","controle vetorial, proteção contra picadas e vacinação conforme recomendação vigente","monitorar perfusão, diurese, hematócrito e sinais de sobrecarga"),
  p("end-06","Endocrinologia","Urgências tireoidianas","Tempestade tireotóxica","febre alta, taquiarritmia, agitação e insuficiência cardíaca em pessoa com tireotoxicose","descompensação multissistêmica aguda do hipertireoidismo","diagnóstico clínico apoiado por função tireoidiana, sem esperar resultado para tratar","betabloqueio quando seguro, tionamida, iodo após tionamida, corticoide e tratamento do precipitante","choque, arritmia, insuficiência hepática e morte","infecção, cirurgia, parto ou suspensão de antitireoidiano","controle adequado do hipertireoidismo e preparo antes de procedimentos","monitorar temperatura, ritmo, função orgânica e resolução do fator precipitante"),
  p("gas-06","Gastroenterologia","Hemorragia digestiva","Hemorragia digestiva alta por varizes","cirrose com hematêmese volumosa e instabilidade","sangramento portal com alto risco de ressangramento e infecção","estabilização, hemograma/coagulação e endoscopia após medidas iniciais","droga vasoativa, antibiótico, ligadura endoscópica e ressuscitação restritiva individualizada","choque, aspiração, encefalopatia e ressangramento","cirrose com hipertensão portal e varizes de alto risco","betabloqueador não seletivo ou ligadura para profilaxia conforme o cenário","prevenção secundária combinada e avaliação da doença hepática"),
  p("nef-06","Nefrologia","Glomerulopatias","Síndrome nefrítica aguda","hematúria glomerular, hipertensão, edema e redução da função renal","cilindros hemáticos e hemácias dismórficas com proteinúria geralmente subnefrótica","urina, função renal, complemento, sorologias dirigidas e biópsia quando indicada","controle de volume/pressão e tratamento específico da causa","edema pulmonar, hipercalemia e perda rápida da função renal","infecção recente, autoimunidade e vasculite","tratar infecções e doenças sistêmicas; não há prevenção universal","seguir creatinina, sedimento, proteinúria e pressão arterial"),
  p("ped-06","Pediatria","Vias aéreas","Crupe viral","criança pequena com tosse ladrante, rouquidão e estridor após pródromo viral","estridor inspiratório por edema subglótico","diagnóstico clínico; radiografia não é necessária na apresentação típica","dexametasona; adrenalina nebulizada se moderado/grave, com observação","obstrução de via aérea e fadiga respiratória","idade entre seis meses e três anos e infecção viral","higiene das mãos, sem profilaxia específica","reavaliar estridor em repouso e recorrência após adrenalina"),
  p("obs-06","Obstetrícia","Hemorragias","Placenta prévia","sangramento vaginal vermelho vivo, indolor, na segunda metade da gestação","placenta cobrindo ou próxima ao orifício cervical interno","ultrassom transvaginal, evitando toque vaginal digital até excluir o diagnóstico","estabilização, vigilância e cesariana no momento indicado ou antes se hemorragia importante","hemorragia materna, prematuridade e acretismo placentário","cesariana prévia, multiparidade e placenta prévia anterior","reduzir cesarianas sem indicação e tabagismo; prevenção completa não é possível","monitorar sangramento, anemia, localização placentária e crescimento fetal"),
  p("onc-06","Oncologia","Emergências oncológicas","Hipercalcemia da malignidade","câncer com confusão, constipação, poliúria, desidratação e cálcio muito elevado","hipercalcemia sintomática mediada por PTHrP, lise óssea ou calcitriol","cálcio corrigido/ionizado, função renal, ECG e investigação do mecanismo","cristaloide, agente antirreabsortivo e calcitonina nos casos graves, além de tratar o tumor","arritmia, coma e injúria renal","tumores escamosos, mieloma e metástases ósseas","controle da neoplasia e evitar desidratação/suplementação excessiva","recontrolar cálcio, rim e efeito do tratamento antitumoral"),

  p("isc-01","Cardiologia","Doença isquêmica","Angina estável","dor retroesternal previsível aos esforços que melhora com repouso","isquemia por demanda sem necrose miocárdica aguda","estratificação clínica e teste funcional ou anatômico conforme probabilidade e risco","controle de sintomas com antianginoso e prevenção de eventos com manejo intensivo de risco","síndrome coronariana aguda e limitação funcional","aterosclerose, diabetes, tabagismo, hipertensão e dislipidemia","atividade física orientada, não fumar e controlar fatores de risco","reavaliar sintomas, adesão e indicação de investigação invasiva"),
  p("isc-02","Cardiologia","Doença isquêmica","Infarto sem supra de ST","dor isquêmica com troponina dinâmica e ausência de supra persistente","necrose miocárdica aguda identificada por biomarcador e contexto isquêmico","ECG seriado, troponina e estratificação de risco","antitrombóticos e estratégia invasiva conforme risco, sem fibrinólise","arritmia, insuficiência cardíaca e reinfarto","aterosclerose e ruptura/erosão de placa","prevenção cardiovascular intensiva","seguimento com terapia secundária e reabilitação"),
  p("isc-03","Cardiologia","Doença isquêmica","Angina vasoespástica","dor em repouso, frequentemente noturna, com elevação transitória de ST","espasmo coronariano reversível","ECG durante a dor e angiografia/teste provocativo apenas em contexto especializado","bloqueador de canal de cálcio e nitrato; evitar gatilhos","arritmia ventricular e infarto","tabagismo e drogas vasoconstritoras","cessar tabagismo e evitar cocaína/vasoconstritores","acompanhar recorrência e tolerância ao vasodilatador"),
  p("isc-04","Cardiologia","Doença isquêmica","Infarto de ventrículo direito","infarto inferior com hipotensão, turgência jugular e pulmões limpos","supra em derivações direitas, especialmente V4R","ECG com derivações direitas e ecocardiograma","reperfusão e otimização cautelosa de pré-carga, evitando nitrato na hipotensão","choque, bloqueio atrioventricular e arritmia","oclusão proximal da coronária direita","prevenção secundária após evento aterotrombótico","monitorar hemodinâmica, condução e recuperação ventricular"),

  p("has-01","Cardiologia","Hipertensão arterial","Hipertensão arterial primária","pressão persistentemente elevada sem causa secundária identificável","diagnóstico confirmado com técnica adequada e medidas repetidas","medida de consultório padronizada e MAPA/MRPA quando indicada","mudança de estilo de vida e combinação farmacológica conforme estágio e risco","AVC, infarto, insuficiência cardíaca e doença renal","idade, obesidade, sódio, álcool, sedentarismo e hereditariedade","peso saudável, atividade, menos sódio, moderação de álcool e não fumar","monitorar pressão, adesão, lesão de órgão-alvo e risco cardiovascular"),
  p("has-02","Cardiologia","Hipertensão arterial","Hipertensão resistente","pressão acima da meta apesar de três classes em doses adequadas, incluindo diurético, com adesão confirmada","persistência após excluir erro de medida, efeito do avental e pseudorresistência","MAPA/MRPA, revisão de adesão e investigação de causas secundárias","otimizar diurético e acrescentar antagonista mineralocorticoide quando apropriado","alto risco cardiovascular e renal","apneia do sono, hiperaldosteronismo, doença renal, fármacos e excesso de sal","reduzir sódio, revisar substâncias e tratar a causa","seguir potássio, função renal e resposta fora do consultório"),
  p("has-03","Cardiologia","Hipertensão arterial","Emergência hipertensiva","pressão muito elevada associada a lesão aguda de órgão-alvo","encefalopatia, edema pulmonar, síndrome aórtica ou isquemia aguda relacionada à pressão","avaliação dirigida ao órgão acometido, ECG, rim, fundo de olho e imagem conforme sintomas","anti-hipertensivo intravenoso titulável com meta de redução específica ao cenário","AVC, dissecção, edema pulmonar e injúria renal","hipertensão não tratada, droga simpaticomimética e doença renal","controle longitudinal e acesso regular a medicamentos","monitorização contínua e transição segura para esquema oral"),
  p("has-04","Cardiologia","Hipertensão arterial","Hiperaldosteronismo primário","hipertensão resistente com hipocalemia e alcalose metabólica","renina suprimida com aldosterona inapropriadamente elevada","relação aldosterona-renina, confirmação e imagem/amostragem conforme caso","antagonista mineralocorticoide ou adrenalectomia na doença unilateral selecionada","fibrilação atrial, AVC e dano renal além do efeito pressórico","adenoma produtor ou hiperplasia adrenal bilateral","não há prevenção específica","monitorar pressão, potássio e resposta após terapia"),

  p("ecg-01","Cardiologia","Eletrocardiograma","Bloqueio atrioventricular total","bradicardia com ondas P e complexos QRS sem relação fixa","dissociação atrioventricular","ECG de 12 derivações e investigação da causa reversível","marcapasso temporário se instável e definitivo quando indicado","síncope, assistolia e morte súbita","fibrose do sistema de condução, infarto e fármacos bloqueadores","uso seguro de fármacos e tratamento da cardiopatia","avaliar dispositivo, sintomas e causa de base"),
  p("ecg-02","Cardiologia","Eletrocardiograma","Hipercalemia com alteração eletrocardiográfica","fraqueza com ondas T apiculadas evoluindo para alargamento do QRS","progressão de T apiculada para perda de P e padrão sinusoidal","ECG imediato e potássio, repetindo amostra se hemólise","cálcio intravenoso e medidas para deslocar/remover potássio","fibrilação ventricular e assistolia","doença renal, fármacos e lise celular","monitorar rim, dieta e medicamentos conforme risco","repetir ECG e potássio por risco de rebote"),
  p("ecg-03","Cardiologia","Eletrocardiograma","Pericardite no ECG","dor pleurítica com supra difuso côncavo e depressão de PR","alterações difusas sem padrão territorial recíproco típico de infarto","ECG seriado e ecocardiograma para avaliar derrame","anti-inflamatório e colchicina nos casos apropriados","derrame, tamponamento e recorrência","infecção viral, autoimunidade e lesão cardíaca","tratar causa e restringir esforço durante atividade","seguir sintomas, inflamação e derrame"),
  p("ecg-04","Cardiologia","Eletrocardiograma","Taquicardia ventricular monomórfica","taquicardia regular de QRS largo em pessoa com infarto prévio","dissociação AV, batimentos de captura ou fusão favorecem origem ventricular","ECG e avaliação hemodinâmica imediata","cardioversão sincronizada se instável; antiarrítmico conforme cenário se estável","degeneração para fibrilação ventricular e choque","cicatriz de infarto e cardiomiopatia","tratar cardiopatia e avaliar desfibrilador implantável","investigar causa, função ventricular e risco de recorrência"),

  p("avc-01","Neurologia","Doenças cerebrovasculares","Síndrome da artéria cerebral média","hemiparesia e perda sensitiva predominando em face e braço, com afasia se hemisfério dominante","déficit cortical lateral com alteração de linguagem ou negligência","TC sem contraste e angiografia cerebral na fase aguda","reperfusão quando elegível e cuidado em unidade de AVC","edema maligno, disfagia e incapacidade","fibrilação atrial e aterosclerose carotídea","controle de fatores e antitrombótico conforme etiologia","reabilitação de linguagem, deglutição e função motora"),
  p("avc-02","Neurologia","Doenças cerebrovasculares","Síndrome da artéria cerebral anterior","fraqueza e perda sensitiva predominando na perna, abulia e incontinência","comprometimento frontal medial e do membro inferior contralateral","imagem cerebral e vascular","reperfusão aguda quando elegível e prevenção secundária etiológica","abulia persistente, quedas e perda funcional","cardioembolia e doença aterosclerótica","controle vascular e antitrombótico apropriado","reabilitar marcha, função executiva e continência"),
  p("avc-03","Neurologia","Doenças cerebrovasculares","Síndrome da artéria cerebral posterior","hemianopsia homônima contralateral com força preservada ou alteração de memória","déficit visual cortical; alexia sem agrafia na lesão dominante esplenial","TC/ressonância e imagem vascular","reperfusão conforme tempo, vaso e elegibilidade","perda visual, alteração cognitiva e dor talâmica","embolia e aterosclerose vertebrobasilar","prevenção secundária conforme mecanismo","reabilitação visual e avaliação cognitiva"),
  p("avc-04","Neurologia","Doenças cerebrovasculares","Hemorragia intracerebral hipertensiva","déficit focal súbito, cefaleia e vômitos com sangue intraparenquimatoso na TC","hematoma profundo em putâmen, tálamo, ponte ou cerebelo","tomografia sem contraste e angiografia em casos selecionados","controle pressórico, reversão de anticoagulação e neurocirurgia conforme localização/gravidade","expansão do hematoma, hidrocefalia e herniação","hipertensão crônica e anticoagulação","controle rigoroso da pressão e uso seguro de anticoagulantes","imagem de controle quando indicada e reabilitação"),

  p("nat-01","Neurologia","Neuroanatomia","Lesão da cápsula interna","hemiparesia pura densa de face, braço e perna sem sinais corticais","fibras motoras compactadas no braço posterior e joelho da cápsula","ressonância cerebral e avaliação vascular","manejo de AVC e reabilitação conforme etiologia","espasticidade, contraturas e incapacidade","doença de pequenas artérias por hipertensão/diabetes","controle vascular","acompanhar recuperação motora e prevenir complicações"),
  p("nat-02","Neurologia","Neuroanatomia","Síndrome bulbar lateral","vertigem, disfagia, ataxia ipsilateral e perda de dor facial ipsilateral/corporal contralateral","lesão dorsolateral do bulbo, geralmente território PICA/vertebral","ressonância com imagem vascular","manejo agudo de AVC e proteção de via aérea/deglutição","aspiração, pneumonia e instabilidade autonômica","doença vertebrobasilar e dissecção","controle vascular e evitar manipulação cervical traumática","reabilitação vestibular e da deglutição"),
  p("nat-03","Neurologia","Neuroanatomia","Lesão do nervo radial","punho caído após compressão do braço, com alteração sensitiva dorsal da mão","fraqueza de extensores do punho e dedos","exame neurológico e eletroneuromiografia se persistente ou localização incerta","retirar compressão, órtese e reabilitação; cirurgia se lesão estrutural","contratura e perda funcional da mão","fratura de úmero e compressão prolongada","posicionamento seguro e proteção em trauma","seguir recuperação motora e sinais de reinervação"),
  p("nat-04","Neurologia","Neuroanatomia","Lesão do quiasma óptico","perda progressiva dos campos temporais de ambos os olhos","hemianopsia bitemporal por compressão de fibras nasais cruzadas","campimetria e ressonância de sela túrcica","tratar a causa compressiva, frequentemente adenoma hipofisário","perda visual permanente e disfunção hipofisária","massa selar e craniofaringioma","não há prevenção específica","acompanhar campos visuais e função hipofisária"),

  p("nfi-01","Neurologia","Neurofisiologia","Potencial de ação neuronal","despolarização rápida seguida de repolarização em resposta a estímulo limiar","entrada rápida de sódio e saída posterior de potássio por canais voltagem-dependentes","registro eletrofisiológico em contexto experimental ou estudo de condução no nervo","corrigir a causa quando canalopatia ou distúrbio eletrolítico altera excitabilidade","falha de condução, fraqueza ou arritmia conforme o tecido","alterações de canais, eletrólitos, toxinas e fármacos","uso seguro de medicamentos e controle eletrolítico","monitorar função clínica e eletrofisiológica conforme doença"),
  p("nfi-02","Neurologia","Neurofisiologia","Transmissão na junção neuromuscular","liberação de acetilcolina gera potencial de placa e contração muscular","entrada de cálcio pré-sináptico e ativação de receptor nicotínico pós-sináptico","estimulação repetitiva e eletromiografia de fibra única em doenças da junção","tratamento depende de mecanismo pré ou pós-sináptico","fraqueza bulbar e respiratória","autoanticorpos, toxina botulínica e fármacos bloqueadores","evitar toxinas/fármacos precipitantes","acompanhar força e capacidade respiratória"),
  p("nfi-03","Neurologia","Neurofisiologia","Reflexo miotático","estiramento súbito de tendão produz contração do músculo correspondente","aferente Ia do fuso faz sinapse com neurônio motor alfa","exame dos reflexos profundos e manobras de reforço","tratar a lesão neurológica subjacente quando o reflexo está alterado","hiperreflexia em lesão piramidal ou hiporreflexia em arco periférico","lesões centrais/periféricas e distúrbios metabólicos","prevenção depende da causa neurológica","comparar simetria, tônus e outros sinais localizatórios"),
  p("nfi-04","Neurologia","Neurofisiologia","Via da dor e temperatura","estímulo nocivo ascende no sistema anterolateral após cruzar na medula","fibras espinotalâmicas cruzam pela comissura anterior poucos níveis após entrada","exame sensitivo comparando dor, temperatura e nível medular","tratar a causa da lesão ou da dor com abordagem multimodal","dor neuropática e perda de proteção térmica","lesão medular, neuropatia e siringomielia","prevenir trauma em áreas insensíveis","mapear nível e evolução do déficit sensitivo"),

  p("ort-sem-01","Ortopedia","Semiologia ortopédica","Lesão do ligamento cruzado anterior","entorse com estalo, hemartrose precoce e sensação de falseio","teste de Lachman com translação anterior aumentada e fim macio","exame comparativo e ressonância quando muda planejamento","reabilitação e reconstrução conforme instabilidade e demanda","instabilidade rotacional e lesão meniscal secundária","esporte com pivô e aterrissagem inadequada","treino neuromuscular e técnica esportiva","avaliar estabilidade, força e retorno seguro ao esporte"),
  p("ort-sem-02","Ortopedia","Semiologia ortopédica","Síndrome do impacto subacromial","dor no arco de elevação do ombro e piora acima da cabeça","testes de Neer/Hawkins reproduzem dor, sem confirmar isoladamente","exame do manguito e ultrassom/ressonância se trauma, fraqueza ou falha terapêutica","modificação de atividade, analgesia e fisioterapia","rigidez, perda funcional e rotura do manguito associada","atividade repetitiva acima da cabeça e discinesia escapular","condicionamento e técnica ergonômica","reavaliar força, amplitude e sinais de rotura"),
  p("ort-sem-03","Ortopedia","Semiologia ortopédica","Radiculopatia lombar","dor irradiada abaixo do joelho em dermátomo com possível déficit reflexo/motor","Lasègue reproduz dor radicular por tensão neural","exame neurológico; ressonância se déficit grave, sinais de alarme ou persistência","manter atividade tolerada, analgesia e reabilitação; cirurgia em indicações específicas","déficit motor persistente e síndrome da cauda equina","hérnia discal e estenose foraminal","ergonomia e condicionamento, sem prevenção completa","seguir força, reflexos, sensibilidade e sinais esfincterianos"),
  p("ort-sem-04","Ortopedia","Semiologia ortopédica","Osteoartrite do quadril","dor inguinal mecânica com limitação de rotação interna","redução dolorosa da rotação interna e teste FABER/FADIR alterado conforme origem","radiografia em carga e exame para diferenciar coluna/partes moles","exercício, peso saudável, analgesia e artroplastia em doença avançada","limitação funcional, quedas e perda de mobilidade","idade, obesidade, displasia e trauma prévio","peso saudável, atividade e prevenção de trauma","acompanhar dor, função e necessidade de cirurgia"),

  p("pne-sem-01","Pneumologia","Semiologia e classificações","Distúrbio ventilatório obstrutivo","espirometria com relação VEF1/CVF reduzida","limitação ao fluxo expiratório, com reversibilidade variável","espirometria pré e pós-broncodilatador","tratar a causa, como asma ou DPOC, e corrigir técnica inalatória","aprisionamento aéreo e insuficiência respiratória","tabagismo, atopia e exposição ocupacional conforme etiologia","não fumar e reduzir exposições","seguir sintomas, exacerbações e espirometria quando indicada"),
  p("pne-sem-02","Pneumologia","Semiologia e classificações","Distúrbio ventilatório restritivo","volumes pulmonares reduzidos com relação VEF1/CVF preservada ou elevada","capacidade pulmonar total reduzida confirma restrição","pletismografia/medida de volumes e difusão, além de imagem conforme hipótese","tratar doença intersticial, pleural, neuromuscular ou obesidade causal","hipoxemia e hipertensão pulmonar","doença intersticial, deformidade torácica, neuromuscular e obesidade","reduzir exposições e tratar doença de base","acompanhar volumes, difusão, oxigenação e progressão"),
  p("pne-sem-03","Pneumologia","Semiologia e classificações","Derrame pleural exsudativo","macicez à percussão e redução do murmúrio com líquido pleural","critérios de Light positivos indicam exsudato","ultrassom e toracocentese diagnóstica quando indicada","tratar causa e drenar se complicado, volumoso sintomático ou empiema","empiema, encarceramento pulmonar e insuficiência respiratória","pneumonia, câncer, tuberculose e embolia pulmonar","prevenção depende da doença causal","reavaliar líquido, sintomas e imagem"),
  p("pne-sem-04","Pneumologia","Semiologia e classificações","Insuficiência respiratória hipercápnica","sonolência, asterixis e gasometria com PaCO2 elevada e acidemia","falha ventilatória alveolar com retenção de dióxido de carbono","gasometria e avaliação da causa/gravidade","suporte ventilatório, frequentemente VNI se apropriada, e tratamento do precipitante","narcose por CO2, parada respiratória e arritmia","DPOC exacerbada, depressor central e doença neuromuscular","vacinação, cessar tabagismo e uso seguro de sedativos","monitorar consciência, gasometria e trabalho respiratório")
];

const sources = {
  "Cardiologia": "edital OMED e diretrizes cardiovasculares vigentes",
  "Pneumologia": "edital OMED, GINA e GOLD",
  "Neurologia": "edital OMED e protocolos neurológicos oficiais",
  "Infectologia": "edital OMED, Ministério da Saúde e OMS",
  "Endocrinologia": "edital OMED e diretrizes endocrinológicas vigentes",
  "Gastroenterologia": "edital OMED e diretrizes gastroenterológicas vigentes",
  "Nefrologia": "edital OMED e KDIGO",
  "Pediatria": "edital OMED, Ministério da Saúde e SBP",
  "Obstetrícia": "edital OMED e diretrizes nacionais de assistência obstétrica",
  "Urgência e Emergência": "edital OMED e AHA Guidelines",
  "Oncologia": "edital OMED e DDT/PCDT do Ministério da Saúde"
};

const kinds = [
  ["diagnosis", profile => `Qual é o diagnóstico mais provável diante de ${profile.vignette}?`, "condition", "O conjunto clínico descrito é característico de"],
  ["hallmark", profile => `Qual achado melhor caracteriza ${profile.condition}?`, "hallmark", "O achado-chave é"],
  ["test", profile => `Qual é a estratégia diagnóstica mais apropriada na suspeita de ${profile.condition}?`, "test", "A investigação recomendada é"],
  ["treatment", profile => `Qual é a conduta inicial ou tratamento central para ${profile.condition}?`, "treatment", "A conduta prioritária é"],
  ["complication", profile => `Qual complicação relevante deve ser antecipada em ${profile.condition}?`, "complication", "Entre as complicações importantes estão"],
  ["risk", profile => `Qual conjunto contém fatores de risco reconhecidos para ${profile.condition}?`, "risk", "Os fatores de risco incluem"],
  ["prevention", profile => `Qual medida de prevenção ou redução de risco se aplica a ${profile.condition}?`, "prevention", "A medida preventiva apropriada é"],
  ["followup", profile => `Após o manejo inicial de ${profile.condition}, qual seguimento é mais adequado?`, "followUp", "O acompanhamento deve incluir"]
];

function rotate(values, index) {
  const shift = index % values.length;
  return [...values.slice(shift), ...values.slice(0, shift)];
}

export const omedProfileQuestions = profiles.flatMap((profile, profileIndex) => {
  const peers = profiles.filter(item => item.area === profile.area && item.id !== profile.id);
  return kinds.map(([kind, prompt, field, rationale], kindIndex) => {
    const correct = profile[field];
    const distractors = peers
      .map(item => item[field])
      .filter(value => value && value !== correct)
      .slice((profileIndex + kindIndex) % Math.max(1, peers.length), (profileIndex + kindIndex) % Math.max(1, peers.length) + 3);
    while (distractors.length < 3) {
      const fallback = peers[distractors.length % peers.length]?.[field];
      if (fallback && !distractors.includes(fallback)) distractors.push(fallback);
      else distractors.push("conduta ou achado não correspondente ao cenário apresentado");
    }
    const answerPosition = (profileIndex + kindIndex) % 4;
    const options = rotate([correct, ...distractors.slice(0, 3)], 4 - answerPosition);
    return {
      id: `omed-profile-${profile.id}-${kind}`,
      area: profile.area,
      topic: profile.topic,
      difficulty: kindIndex < 2 ? "Fácil" : kindIndex < 6 ? "Média" : "Difícil",
      tag: "OMED",
      text: prompt(profile),
      options,
      answer: options.indexOf(correct),
      explanation: `${rationale} ${correct}. A escolha decorre do objetivo clínico específico do enunciado, enquanto as demais alternativas pertencem a outros cenários da mesma área. Fonte-base: ${sources[profile.area] || "edital OMED e diretrizes oficiais da especialidade"}.`
    };
  });
});
