const q = (id, area, topic, difficulty, text, options, answer, explanation) => ({
  id: `omed-extra-${id}`, area, topic, difficulty, tag: "OMED", text, options, answer, explanation
});

export const omedSupplemental = [
  q("pneumo-01","Pneumologia","Pneumotórax","Média","Jovem alto e magro apresenta dor torácica súbita e redução do murmúrio vesicular à esquerda, sem instabilidade. A radiografia confirma pequeno pneumotórax primário. Qual princípio orienta a conduta?",["Observar ou aspirar conforme tamanho e sintomas","Trombolisar imediatamente","Iniciar diurético","Realizar toracotomia em todos"],0,"Pneumotórax primário pequeno e pouco sintomático pode ser manejado conservadoramente; a conduta depende do tamanho, sintomas e estabilidade."),
  q("pneumo-02","Pneumologia","Pneumonia adquirida na comunidade","Média","Idoso com pneumonia apresenta confusão, ureia elevada, FR 34 irpm, PA 88×56 mmHg e 67 anos. O que o CURB-65 sugere?",["Baixo risco e alta automática","Maior gravidade e necessidade de avaliação hospitalar","Diagnóstico de tuberculose","Ausência de infecção bacteriana"],1,"Cada um dos cinco critérios soma um ponto; pontuação elevada indica maior mortalidade e favorece internação."),
  q("pneumo-03","Pneumologia","Asma","Média","Mulher com sintomas variáveis, piora noturna e espirometria obstrutiva apresenta aumento significativo do VEF1 após broncodilatador. Qual diagnóstico é favorecido?",["Asma","Fibrose pulmonar","Derrame pleural","Embolia pulmonar crônica"],0,"Obstrução variável e reversibilidade significativa após broncodilatador sustentam o diagnóstico de asma."),
  q("pneumo-04","Pneumologia","Tuberculose","Difícil","Paciente com HIV inicia tratamento para tuberculose. Qual preocupação deve orientar o momento de introdução da terapia antirretroviral?",["Risco de síndrome inflamatória de reconstituição imune","Risco de pneumotórax espontâneo","Impossibilidade absoluta de combinar os tratamentos","Necessidade de suspender todo tratamento da TB"],0,"A TARV deve ser introduzida oportunamente, considerando imunossupressão, interações e risco de reconstituição imune; não se abandona o tratamento da TB."),
  q("pneumo-05","Pneumologia","Distúrbios ácido-base","Difícil","Gasometria mostra pH 7,28, HCO₃⁻ 16 mEq/L e PaCO₂ 32 mmHg. Qual distúrbio primário está presente?",["Acidose metabólica","Alcalose metabólica","Acidose respiratória isolada","Alcalose respiratória isolada"],0,"A acidemia acompanhada de bicarbonato reduzido indica acidose metabólica; a PaCO₂ deve ser avaliada pela compensação esperada."),
  q("pneumo-06","Pneumologia","Tosse crônica","Fácil","Paciente desenvolve tosse seca persistente meses após iniciar enalapril, sem alterações radiográficas. Qual troca é mais apropriada?",["Substituir o IECA por um BRA","Associar outro IECA","Iniciar antibiótico contínuo","Suspender todo anti-hipertensivo"],0,"A tosse por IECA decorre do acúmulo de bradicinina; um BRA mantém bloqueio do SRAA com menor risco de tosse."),

  q("cardio-01","Cardiologia","Fibrilação atrial","Média","Paciente com fibrilação atrial apresenta frequência ventricular elevada, hipotensão e dor torácica isquêmica. Qual conduta é prioritária?",["Cardioversão elétrica sincronizada","Apenas anticoagulação oral","Teste ergométrico","Observação sem intervenção"],0,"Taquiarritmia com instabilidade hemodinâmica exige cardioversão sincronizada imediata."),
  q("cardio-02","Cardiologia","Taquiarritmias","Média","Paciente estável apresenta taquicardia regular de QRS estreito. Manobras vagais não reverteram o ritmo. Qual medicamento é a próxima opção?",["Adenosina","Atropina","Bicarbonato","Furosemida"],0,"Na taquicardia supraventricular regular e estável, adenosina é indicada após falha das manobras vagais."),
  q("cardio-03","Cardiologia","Insuficiência cardíaca","Difícil","Homem com ICFER permanece sintomático. Qual conjunto representa os pilares terapêuticos modificadores de prognóstico?",["ARNI/IECA/BRA, betabloqueador, antagonista mineralocorticoide e iSGLT2","AAS, nitrato, digoxina e diurético","Estatina, fibrato, anticoagulante e amiodarona","Diurético isolado em dose máxima"],0,"Os quatro pilares da ICFER atuam em vias complementares e reduzem mortalidade e hospitalizações."),
  q("cardio-04","Cardiologia","Pericardite aguda","Média","Paciente apresenta dor torácica que melhora ao sentar e inclinar-se para frente, atrito pericárdico e supra de ST difuso. Qual tratamento inicial é habitual?",["AINE associado a colchicina","Trombólise","Antibiótico por seis meses","Marcapasso definitivo"],0,"O quadro é típico de pericardite aguda, geralmente tratada com anti-inflamatório e colchicina quando não há contraindicação."),
  q("cardio-05","Cardiologia","Doença arterial periférica","Média","Tabagista relata dor em panturrilha ao caminhar, que desaparece com repouso. Qual exame simples auxilia a confirmação?",["Índice tornozelo-braquial","Eletroencefalograma","Espirometria","Endoscopia digestiva"],0,"O índice tornozelo-braquial é um teste não invasivo fundamental na avaliação da doença arterial periférica."),
  q("cardio-06","Cardiologia","Febre reumática","Média","Adolescente apresenta poliartrite migratória e cardite semanas após faringite estreptocócica. Qual conjunto de critérios organiza o diagnóstico?",["Critérios de Jones","Critérios de Light","Escore de Wells","Classificação de Hinchey"],0,"Os critérios de Jones combinam manifestações maiores, menores e evidência de infecção estreptocócica prévia."),

  q("ped-01","Pediatria","Bronquiolite","Média","Lactente de cinco meses tem primeiro episódio de sibilância após coriza, com esforço respiratório leve e boa oxigenação. Qual princípio terapêutico predomina?",["Suporte, hidratação e higiene nasal","Antibiótico obrigatório","Corticoide sistêmico rotineiro","Broncodilatador contínuo para todos"],0,"Na bronquiolite típica, o tratamento é principalmente de suporte; intervenções farmacológicas rotineiras têm pouco benefício."),
  q("ped-02","Pediatria","Icterícia neonatal","Difícil","Recém-nascido apresenta icterícia nas primeiras 18 horas de vida. Como esse achado deve ser interpretado?",["Patológico até prova em contrário","Fisiológico em todos os casos","Sem necessidade de dosar bilirrubina","Indicação automática de alta"],0,"Icterícia nas primeiras 24 horas é precoce e exige investigação de hemólise e outras causas patológicas."),
  q("ped-03","Pediatria","Reanimação neonatal","Média","Recém-nascido permanece apneico e com FC de 80 bpm após os passos iniciais da reanimação. Qual intervenção é prioritária?",["Ventilação com pressão positiva","Massagem cardíaca isolada","Adrenalina antes de ventilar","Apenas oxigênio próximo à face"],0,"A ventilação efetiva é a intervenção mais importante quando há apneia ou FC menor que 100 bpm."),
  q("ped-04","Pediatria","Asma pediátrica","Difícil","Criança com crise de asma mantém desconforto importante após broncodilatadores e corticoide, sem sinais imediatos de falência. Qual adjuvante pode ser considerado em crise grave?",["Sulfato de magnésio intravenoso","Antibiótico em todos os casos","Antitussígeno opioide","Diurético de alça"],0,"O magnésio intravenoso pode ser usado como adjuvante em exacerbação grave refratária ao tratamento inicial."),
  q("ped-05","Pediatria","Doença de Kawasaki","Média","Criança apresenta febre prolongada, conjuntivite não purulenta, alterações orais, exantema e edema de extremidades. Qual complicação preocupa mais?",["Aneurisma de artéria coronária","Cirrose hepática","Pneumotórax","Glomerulopatia membranosa"],0,"A doença de Kawasaki é uma vasculite com risco de aneurismas coronarianos; imunoglobulina precoce reduz esse risco."),

  q("infecto-01","Infectologia","Meningites","Difícil","Adulto com febre, rigidez de nuca e rebaixamento do nível de consciência apresenta papiledema. Qual sequência é mais segura?",["Coletar sangue, iniciar tratamento e obter neuroimagem antes da punção","Punção lombar imediata antes de qualquer medida","Aguardar cultura por 48 horas","Dar alta com sintomáticos"],0,"Sinais de hipertensão intracraniana indicam neuroimagem antes da punção; antibiótico não deve ser atrasado."),
  q("infecto-02","Infectologia","Sífilis","Média","Gestante tem teste treponêmico e não treponêmico reagentes, sem comprovação de tratamento prévio. Qual fármaco é essencial para prevenir sífilis congênita?",["Penicilina benzatina","Doxiciclina","Ciprofloxacino","Azitromicina em dose única como equivalente"],0,"A penicilina é o tratamento comprovado para a gestante e para prevenção da transmissão vertical."),
  q("infecto-03","Infectologia","HIV e infecções oportunistas","Média","Pessoa com HIV, CD4 muito baixo, apresenta dispneia subaguda, tosse seca e infiltrado intersticial bilateral. Qual hipótese é clássica?",["Pneumocistose","Derrame transudativo","Crise asmática isolada","Pneumotórax traumático"],0,"Pneumocystis jirovecii causa pneumonia subaguda com hipoxemia e infiltrado bilateral em imunossupressão avançada."),
  q("infecto-04","Infectologia","Infecção urinária","Média","Gestante assintomática apresenta urocultura com bacteriúria significativa. Qual conduta é adequada?",["Tratar com antimicrobiano seguro na gestação","Não tratar por ausência de sintomas","Solicitar apenas nova cultura após o parto","Usar fluoroquinolona obrigatoriamente"],0,"Bacteriúria assintomática na gestação deve ser tratada para reduzir pielonefrite e complicações obstétricas."),
  q("infecto-05","Infectologia","Endocardite infecciosa","Difícil","Usuário de droga intravenosa apresenta febre, bacteremia por S. aureus e vegetação em valva tricúspide. Qual fenômeno embólico é mais esperado?",["Êmbolos sépticos pulmonares","Isquemia mesentérica obrigatória","AVC por carótida em todos","Trombose portal isolada"],0,"Endocardite direita, especialmente tricúspide, pode lançar êmbolos sépticos para a circulação pulmonar."),
  q("infecto-06","Infectologia","Profilaxia pós-exposição","Difícil","Pessoa não vacinada sofre mordedura profunda por cão desconhecido que não pode ser observado. Qual prevenção deve ser avaliada?",["Vacina e imunoglobulina antirrábica conforme classificação da exposição","Apenas antibiótico tópico","Nenhuma medida se a ferida for lavada","Vacina contra febre amarela"],0,"Exposição grave a animal suspeito ou não observável pode exigir vacina e imunoglobulina, além de limpeza rigorosa da ferida."),

  q("cir-01","Cirurgia Geral","Hérnias","Média","Paciente com hérnia inguinal apresenta dor intensa, massa irredutível, vômitos e sinais de sofrimento sistêmico. Qual complicação é provável?",["Estrangulamento herniário","Hérnia redutível simples","Diástase abdominal","Lipoma assintomático"],0,"Dor, irredutibilidade e obstrução sugerem encarceramento; sinais sistêmicos ou isquemia apontam estrangulamento e exigem cirurgia urgente."),
  q("cir-02","Cirurgia Geral","Litíase urinária","Média","Paciente com cólica renal apresenta febre, hipotensão e hidronefrose por cálculo ureteral. Qual é a prioridade?",["Descompressão urgente do trato urinário e antibiótico","Apenas analgesia domiciliar","Litotripsia eletiva sem tratar a infecção","Aumentar ingestão hídrica e aguardar"],0,"Infecção associada a obstrução urinária é emergência: requer antibiótico e drenagem por cateter ou nefrostomia."),
  q("cir-03","Cirurgia Geral","Cuidado perioperatório","Fácil","Qual classificação é usada para comunicar o estado físico pré-operatório do paciente?",["ASA","Glasgow","Child-Pugh exclusivamente","Bishop"],0,"A classificação ASA estratifica o estado físico e auxilia a comunicação do risco anestésico."),
  q("cir-04","Cirurgia Geral","Diverticulite","Difícil","Paciente com diverticulite apresenta abscesso pericólico pequeno e localizado, sem peritonite difusa. Qual classificação é frequentemente utilizada?",["Hinchey","Stanford","Jones","Westley"],0,"A classificação de Hinchey organiza a diverticulite complicada conforme abscesso e extensão da peritonite."),
  q("cir-05","Cirurgia Geral","Embolia gordurosa","Média","Após fratura de fêmur, jovem evolui em 48 horas com hipoxemia, alteração neurológica e petéquias. Qual diagnóstico é mais provável?",["Síndrome de embolia gordurosa","Choque anafilático","Meningite bacteriana","Crise tireotóxica"],0,"A tríade respiratória, neurológica e petequial após fratura de osso longo é clássica da embolia gordurosa."),

  q("mfc-01","Medicina de Família e Comunidade","Medidas de associação","Média","Em uma coorte, a incidência foi 20% nos expostos e 5% nos não expostos. Qual é o risco relativo?",["4","0,25","15","25"],0,"Risco relativo é a incidência nos expostos dividida pela incidência nos não expostos: 0,20/0,05 = 4."),
  q("mfc-02","Medicina de Família e Comunidade","Vieses","Média","Em estudo caso-controle, pacientes doentes lembram exposições passadas com mais detalhe que os controles. Qual viés ocorreu?",["Viés de memória","Viés de publicação","Confusão residual exclusivamente","Erro aleatório de digitação"],0,"A lembrança diferencial de exposições conforme o estado de doença caracteriza viés de memória."),
  q("mfc-03","Medicina de Família e Comunidade","Prevenção","Fácil","Rastreamento de câncer em pessoa assintomática corresponde a qual nível de prevenção?",["Secundária","Primária","Terciária","Quaternária exclusivamente"],0,"Prevenção secundária busca detectar doença em fase pré-clínica para tratamento precoce."),
  q("mfc-04","Medicina de Família e Comunidade","Medicina baseada em evidências","Difícil","Uma meta-análise apresenta I² muito elevado. O que esse resultado sugere?",["Heterogeneidade importante entre os estudos","Ausência total de viés","Efeito obrigatoriamente verdadeiro","Amostras idênticas"],0,"I² elevado indica que boa parte da variabilidade entre os resultados decorre de heterogeneidade, não apenas do acaso."),
  q("mfc-05","Medicina de Família e Comunidade","SUS","Média","O princípio que garante atendimento conforme necessidades diferentes, destinando mais recursos a quem mais precisa, é:",["Equidade","Universalidade","Publicidade","Centralização"],0,"Equidade reconhece necessidades distintas e busca reduzir desigualdades injustas."),

  q("neuro-01","Neurologia","Guillain-Barré","Média","Paciente apresenta fraqueza ascendente simétrica e arreflexia duas semanas após gastroenterite. Qual exame do líquor é típico após a primeira semana?",["Proteína elevada com poucas células","Pleocitose neutrofílica intensa obrigatória","Glicose indetectável","Hemácias em grande quantidade"],0,"A dissociação albuminocitológica, com proteína elevada e celularidade baixa, é característica."),
  q("neuro-02","Neurologia","Miastenia gravis","Média","Mulher apresenta ptose e diplopia que pioram ao longo do dia e melhoram com repouso. Qual mecanismo é mais provável?",["Autoanticorpos contra componentes da junção neuromuscular","Desmielinização de nervos periféricos","Degeneração dopaminérgica nigral","Lesão do trato corticoespinal"],0,"Miastenia causa fraqueza fatigável por autoimunidade pós-sináptica, frequentemente contra receptor de acetilcolina."),
  q("neuro-03","Neurologia","Compressão medular","Difícil","Paciente com câncer apresenta dor lombar, fraqueza progressiva, nível sensitivo e disfunção esfincteriana. Qual medida é urgente?",["Imagem da coluna e tratamento imediato da compressão","Apenas fisioterapia ambulatorial","Punção lombar antes da imagem","Alta com analgésico simples"],0,"Compressão medular é emergência oncológica; exige ressonância urgente e tratamento para preservar função neurológica."),
  q("neuro-04","Neurologia","Síndromes vestibulares","Difícil","Vertigem contínua com nistagmo vertical, ataxia incapacitante e outros déficits neurológicos sugere:",["Causa vestibular central","VPPB típica","Neuronite vestibular sem sinais de alarme","Doença exclusivamente coclear"],0,"Nistagmo vertical e déficits neurológicos são sinais centrais e exigem investigação de circulação posterior."),
  q("neuro-05","Neurologia","Wernicke-Korsakoff","Média","Etilista crônico chega confuso, atáxico e com alterações oculomotoras. Qual tratamento deve preceder a glicose?",["Tiamina","Ácido fólico isolado","Naloxona","Vitamina K"],0,"Tiamina deve ser administrada imediatamente antes ou junto da glicose para evitar agravamento da encefalopatia de Wernicke."),
  q("neuro-06","Neurologia","Cefaleia pós-punção","Média","Após raquianestesia, paciente desenvolve cefaleia que piora em pé e melhora ao deitar. Qual mecanismo é mais provável?",["Perda de líquor pela punção dural","Hemorragia subaracnóidea obrigatória","Hipertensão intracraniana idiopática","Sinusite bacteriana"],0,"A perda de líquor reduz a pressão intracraniana e produz cefaleia ortostática típica."),

  q("go-01","Ginecologia e Obstetrícia","Sangramento na gestação","Difícil","Gestante no terceiro trimestre apresenta sangramento vaginal vermelho vivo, indolor e sem hipertonia uterina. Qual hipótese é mais provável?",["Placenta prévia","Descolamento prematuro de placenta","Ruptura uterina","Corioamnionite"],0,"Sangramento indolor e vermelho vivo no terceiro trimestre é apresentação clássica de placenta prévia."),
  q("go-02","Ginecologia e Obstetrícia","SOP","Média","Mulher com ciclos irregulares, hiperandrogenismo clínico e ovários policísticos procura avaliação. Qual diagnóstico é provável após excluir causas alternativas?",["Síndrome dos ovários policísticos","Insuficiência ovariana obrigatória","Endometriose isolada","Doença inflamatória pélvica"],0,"Dois dos critérios de Rotterdam, após exclusão de diagnósticos diferenciais, sustentam SOP."),
  q("go-03","Ginecologia e Obstetrícia","Endometriose","Média","Mulher apresenta dismenorreia progressiva, dor pélvica crônica, dispareunia profunda e infertilidade. Qual diagnóstico é mais provável?",["Endometriose","Vaginose bacteriana","Cistite simples","Placenta acreta"],0,"A combinação de dismenorreia, dispareunia profunda, dor crônica e infertilidade é típica de endometriose."),
  q("go-04","Ginecologia e Obstetrícia","Câncer do colo uterino","Média","Qual infecção persistente é o principal fator causal do câncer do colo uterino?",["HPV de alto risco","Candida albicans","Trichomonas vaginalis","Herpes simples tipo 1 isoladamente"],0,"A persistência de tipos oncogênicos do HPV, especialmente 16 e 18, é o principal fator causal."),
  q("go-05","Ginecologia e Obstetrícia","Distocia e partograma","Difícil","Durante o trabalho de parto, dilatação e descida fetal deixam de progredir. Qual ferramenta permite acompanhar graficamente essa evolução?",["Partograma","Curva de crescimento infantil","Escore de Wells","Nomograma de bilirrubina"],0,"O partograma registra dilatação, descida, contrações e condições materno-fetais, auxiliando o reconhecimento de distocias."),

  q("psiq-01","Psiquiatria","Psicose puerperal","Difícil","Puérpera, dez dias após o parto, apresenta insônia, agitação, delírios e vozes que ordenam ferir o bebê. Qual conduta é prioritária?",["Internação psiquiátrica urgente e proteção da mãe e do bebê","Reassegurar e rever em um mês","Iniciar antidepressivo isolado em casa","Suspender toda avaliação por ser alteração fisiológica"],0,"Psicose puerperal é emergência com risco de suicídio e infanticídio, exigindo proteção e tratamento hospitalar."),
  q("reumato-01","Reumatologia","Gota","Média","Homem apresenta dor súbita intensa na primeira metatarsofalângica. O líquido sinovial mostra cristais em agulha com birrefringência negativa. Qual diagnóstico?",["Gota","Pseudogota","Artrite séptica confirmada","Osteoartrite"],0,"Cristais de urato monossódico em agulha e birrefringência negativa confirmam gota."),
  q("endo-01","Endocrinologia","Insuficiência adrenal","Difícil","Paciente apresenta hipotensão, hiponatremia, hipercalemia, hipoglicemia e hiperpigmentação. Qual diagnóstico é mais provável?",["Insuficiência adrenal primária","Hipertireoidismo","Hiperaldosteronismo primário","Feocromocitoma"],0,"Deficiência de cortisol e aldosterona com ACTH elevado explica hipotensão, distúrbios eletrolíticos e hiperpigmentação."),
  q("nefro-01","Nefrologia","Injúria renal aguda","Média","Paciente com vômitos prolongados desenvolve oligúria; ureia/creatinina está elevada e o sedimento é inativo. Qual mecanismo é provável?",["IRA pré-renal por hipoperfusão","Necrose cortical irreversível obrigatória","Glomerulonefrite rapidamente progressiva","Obstrução ureteral bilateral comprovada"],0,"Perda volêmica com azotemia desproporcional e sedimento inativo favorece injúria pré-renal."),
  q("hemato-01","Hematologia","Anemia megaloblástica","Média","Paciente apresenta anemia macrocítica, neutrófilos hipersegmentados e parestesias. Qual deficiência é mais provável?",["Vitamina B12","Ferro","Vitamina K","Cobre exclusivamente"],0,"Deficiência de B12 causa megaloblastose e manifestações neurológicas; folato não costuma causar neuropatia."),
  q("onco-01","Oncologia","Linfomas","Média","Adulto jovem apresenta massa mediastinal, linfonodo cervical indolor e sintomas B. A biópsia mostra células de Reed-Sternberg. Qual diagnóstico?",["Linfoma de Hodgkin","Leucemia mieloide crônica","Mieloma múltiplo","PTI"],0,"Células de Reed-Sternberg em contexto compatível são características do linfoma de Hodgkin.")
];
